### PR TITLE
new domain for luggs servers

### PR DESCRIPTION
**Pull request by luggs-co**
Updating server address to new domain, from elec.luggs.co to ex.lug.gs

### CODE REVIEW

**Comment by bauerj** [comment]
Why this change? Is the server still available at the old domain?

**Comment by luggs-co** [comment]
> 
> 
> Why this change? Is the server still available at the old domain?

it won't be no.

**Comment by bauerj** [comment]
Are you still in control of the old domain?

**Comment by luggs-co** [comment]
> 
> 
> Are you still in control of the old domain?

no

**Comment by bauerj** [comment]
I assume you sold your domain to the ones that run the current phishing attack against Electrum users. Is that correct?

**Pull request closed without merging**
