### PR TITLE
Add the "Opendime Helper" plugin for Electrum

### PR DESCRIPTION
**Pull request by peter-conalgo**
A new plugin to support Opendime from inside Electrum.

- once enabled, a new tab is shown (to left of Console tab).
- click "Find Opendime(s)" and any connected Opendime units are found, and verified
- real time balances for those units are shown in a table
- send funds to, or sweep up funds from, any attached device with a click or two
- new units are loaded with 256k bytes of crypto-quality entropy with one click
- performs in-depth verification of device if libusb (PyUSB) is installed

This code is isolated to `plugins/opendime` except for one tiny change that was needed to preload the text of a private key into the sweep dialog. Some very minor bugs in the Electrum main code base are addressed in PR #1888 but this code does not depend on those fixes.

This code will work better and faster if two python dependancies are installed: `PyUSB` (aka. libusb) and `psutil`. However, it already includes workarounds if these are missing. It indicates the status of these modules and encourages the user to install them on the plugin's setting menu. It does not attempt to install the modules itself. There are no real settings for this plugin.

I haven't tested this except on MacOS. However, I wrote it as portably as possible... (famous last words). I'm happy to accept patches for other platforms.

_Aside:_ This is the first time I've looked at Electrum in a long time, and it's become a really capable wallet over the years! That's why I choose it to be the platform for verifying/using Opendime. Keep up the good work @ecdsa and all. 

screen shot 2016-08-08 at 10 46 51 am

### CODE REVIEW

**Comment by ecdsa** [comment]
thanks! can you rebase your code against the 'dev' branch ?
a major refactoring is in there.

**Comment by peter-conalgo** [comment]
Not sure if that really worked... but I tried to rebase it to dev.

**Comment by ecdsa** [comment]
not sure what you did.. I meant to make it mergeable with dev.
Anyway, I will merge the dev branch in about 1 week.

**Comment by peter-conalgo** [comment]
Tried again with new PR #1894

**Pull request closed without merging**
