### PR TITLE
Improve get_target

### PR DESCRIPTION
**Pull request by fanatid**
Need attentive review.

### CODE REVIEW

**Comment by ecdsa** [comment]
good catch. 
there is redundant code between verify_chain and verify_chunk, we should avoid that

**Comment by ecdsa** [comment]
@fanatid I sent you an email, can you answer?

**Comment by ecdsa** [comment]
@fanatid if you have time, please check 2a1fbf01fe63dee9f950f7ba7b4d68d456799262

**Comment by fanatid** [comment]
@ecdsa I checked your commit. Nicely done!
I found two things that make code not clear:
1. function name `verify_headers` -- verify exactly **one** header, not many header**s**
2. in `verify_chunk` you save chunk, although should only verify headers.. `verify_chain` do this in right way

If you want I can make PR with changes.

**Comment by ecdsa** [comment]
please do

**Pull request merged**
