### PR TITLE
network: (nossl) handle_protocol_contradiction

### PR DESCRIPTION
**Pull request by SomberNight**
closes https://github.com/spesmilo/electrum/issues/3706

see https://github.com/spesmilo/electrum/issues/3706#issuecomment-357404512

### CODE REVIEW

**Comment by ecdsa** [comment]
that seems too complicated... 
how about not having conflicts in the first place, by simplifying the syntax?
we could drop the protocol letter in the command line: "electrum -s server:port --nossl"

if a default server is set in config, and it conflicts with the --nossl flag, we can simply fail at connecting

**Comment by SomberNight** [comment]
> we could drop the protocol letter in the command line: "electrum -s server:port --nossl"

Yes that would be fine.

> if a default server is set in config, and it conflicts with the --nossl flag, we can simply fail at connecting

Fail how? Consider the following scenario:
- a GUI user previously unchecked the SSL checkbox, and also right-click "Use as server" -selected a server
- he now upgrades and ... ?

**Comment by SomberNight** [comment]
We could "config-upgrade" the `server` variable to force-drop the protocol letter from there; combined with your proposal.

**Comment by ecdsa** [comment]
well, yes, we can drop the protocol letter from the config, but that will still result in a connection failure, because we don't know the correct port number. I dont think we should try to do better, it is fine to fail in that case.

**Comment by SomberNight** [comment]
Oh right, I see what you mean. Failing to connect is okay. What I wanted to avoid is failing -> raising an exception -> "crashing", or similar.

**Pull request closed without merging**
