### PR TITLE
Add testnet mode to .desktop file

### PR DESCRIPTION
**Pull request by yura-pakhuchiy**
Easy way to start testnet version from linux DE

### CODE REVIEW

**Comment by bauerj** [comment]
Can you show a screenshot? How is this displayed?

**Comment by yura-pakhuchiy** [comment]
It depends on DE, in GNOME3 it looks like this (right click menu on the launcher icon):
screenshot from 2018-03-17 23-15-42

**Comment by ecdsa** [comment]
I don't think this is a good idea..  testnet is for testing, should not be exposted to all users

**Comment by yura-pakhuchiy** [comment]
Testnet can be used not only for testing, it is a great way to try various bitcoin and electrum features without risk of losing money. Bitcoin can be quite confusion to new users, some people prefer learning by trying and testnet works great for that.

**Comment by bauerj** [comment]
It is also exposed to Windows users - why isn't it a problem there?

**Comment by yura-pakhuchiy** [comment]
Besides windows version creates shortcut for testnet mode, why linux version should not?

**Comment by ecdsa** [comment]
@bauerj maybe it is a problem there...

**Comment by yura-pakhuchiy** [comment]
@ecdsa could you explain why testnet should not be available for all users? It is quite useful for learning.

**Comment by yura-pakhuchiy** [comment]
Besides in linux testnet mode appears only in right click menu, not a separate item in list of programs. I do not feel that it is a lot of exposure.

**Comment by ecdsa** [comment]
@yura-pakhuchiy there is a distinction between "not available" and "not availble in the desktop icon menu".
Adding a menu item for every function is how you make an application clogged and unusable.

**Comment by ecdsa** [comment]
anyway, I will still merge it for consistency

**Pull request merged**
