### PR TITLE
Changed color of coin selected in amount dialog in kivy gui.

### PR DESCRIPTION
**Pull request by aldrinpscastro**

### CODE REVIEW

**Comment by SomberNight** [comment]
Could you upload pictures before/after, to compare?

**Comment by aldrinpscastro** [comment]
Captura de tela_2021-01-24_03-10-23v2

**Comment by ecdsa** [comment]
that looks worse to me, not better

**Comment by aldrinpscastro** [comment]
i always get confused if i'm putting value on fiat or btc. I think that is why the previous color stands out a lot. I always think that it is she who is selected.

**Comment by ecdsa** [comment]
the change in font size makes the display unstable.
you do not want a widget to change position when you tap on it.

**Pull request closed without merging**
