### PR TITLE
appimage: Bump git

### PR DESCRIPTION
**Pull request by gruve-p**
https://launchpad.net/ubuntu/+source/git/1:2.17.1-1ubuntu0.12

### CODE REVIEW

**Comment by accumulator** [comment]
Is there a reason git is version-pinned? IMO it doesn't need version pinning for the build to be reproducible

**Comment by gruve-p** [comment]
> Is there a reason git is version-pinned? IMO it doesn't need to be for the build to be reproducible

https://github.com/spesmilo/electrum/issues/7484#issuecomment-914354203

**Comment by accumulator** [comment]
> > Is there a reason git is version-pinned? IMO it doesn't need to be for the build to be reproducible
> 
> [#7484 (comment)](https://github.com/spesmilo/electrum/issues/7484#issuecomment-914354203)

This is not an answer to my question. 

I understand the need to version-pin packages. However the 'git' package IMO shouldn't need to be one of them (as it doesn't influence the binary produced, unless there is a weird corner-case where it touches the source files differently from version to version).

**Comment by SomberNight** [comment]
> Is there a reason git is version-pinned? IMO it doesn't need to be for the build to be reproducible

- Everything is version-pinned because it is difficult to tell what does not need to be pinned.

- Re git specifically, we had an issue at one point about `git describe` not being stable:
  IRC log from `#electrum` on freenode, 2017-11-29:
    ```
    [20:30:35] <ThomasV> arihan: electrum-3.0.2-52-g599c1380.exe
    [20:30:47] <ThomasV> arihan: note how the filename differs?
    [20:31:04] <ThomasV> maybe caused by a different git version
    [20:31:57] <bauerj> ThomasV: Looking into the .exe file didn't provide any useful insight
    [20:32:17] <bauerj> Maybe we can try a build with LZMA and CRC checks disabled to see if that makes things better
    [20:33:37] <ThomasV> bauerj: arihan does not have the same $VERSION string, a trailing zero is missing
    [20:34:24] <ThomasV> bauerj: he has electrum-3.0.2-52-g599c138.exe
    [20:34:41] <bauerj> Maybe a different git version?
    [20:34:50] <bauerj> I'm on 2.15.0
    [20:35:22] <ThomasV> 2.11.0 here
    [20:35:27] <ThomasV> arihan: ^
    [20:37:01] <arihan> ThomasV, bauerj Ah mine says 2.7.4 ?? Seams old then
    [20:38:05] <ThomasV> arihan: "git describe --tags" is used
    [20:38:29] <ThomasV> you seem to have a different result there
    [20:38:38] <arihan> ThomasV, ill try updating git see if it changes it
    [20:39:20] <arihan> Although 2.7.4 seems to be the most recent version in ubuntu... Did you add a ppa or something?
    [20:39:47] <bauerj> Ubuntu 14.04? :P
    [20:39:55] <arihan> 16.04!
    [20:40:34] <ThomasV> arihan: yout pyc files also have different timestamps. we managed to fix that between me and bauerj, should not be too difficult
    [20:42:29] <arihan> Ok on git 2.15 now had to add the gitteams ppa
    [20:42:39] <arihan> ThomasV, how did you change the timestamps?
    [20:42:57] <ThomasV> arihan: we use a custom version of pyinstaller
    ```

- Also see https://github.com/spesmilo/electrum/issues/6747

**Pull request merged**
