### PR TITLE
Add support for Archos Safe-T mini hardware wallet

### PR DESCRIPTION
**Pull request by jcrona**
These commits add support for the Archos Safe-T mini hardware wallet in Electrum. It is based on what has been done for the TREZOR.

https://github.com/archos-safe-t/python-safet is required in order to find a connected Safe-T mini (pip3 install safet).

Here is what it looks like on Testnet:
screenshot_20180614_111622

### CODE REVIEW

**Comment by bauerj** [comment]
Are you working for Archos? As far as I can see, the device is not available for purchase yet.

**Comment by jcrona** [comment]
@bauerj yes I am. The Safe-T mini can now be pre-ordered and will be shipped mid july.

**Comment by SomberNight** [comment]
Thanks for sending devices to test with.
I've done some basic tests and it works as expected; also I diffed the code with the Trezor plugin and the changes are minimal, so overall it looks good.
The main issue I have at the moment is with device initialisation, as I explained privately. Ping me if you think that's fixed.

**Comment by SomberNight** [comment]
Re https://github.com/spesmilo/electrum/pull/4445/commits/01816607e8ba308cb5cff96b5fb844e4f6b8fcc1, could you make rlp optional as it's only needed for ethereum? As in https://github.com/trezor/python-trezor/commit/76fea5afc430b4b42d94dd4540da7074c13a568e 
For the time being, I fixed the rlp version to minimise the number of unneeded dependencies

**Comment by jcrona** [comment]
@SomberNight done, python-safet has been updated to v0.1.3 where rlp is optional.

**Comment by SomberNight** [comment]
merged manually in https://github.com/spesmilo/electrum/commit/02c30e3d520d130866e8edc4cd13eb229a853f49

**Pull request closed without merging**
