### PR TITLE
delete -psn arg on osx, fixes #1080

### LINKED ISSUE #1080: Proxy setup is greyed out in 2.02/Mac 10.10.2
I tried to run latest Electrum in my mac, but unable to connect to server, previous version worked fine.

in network panel, there's a proxy setup but greyed out, I already removed all my proxy settings in system.

here's the screenshot
https://www.amazon.com/clouddrive/share/I_ZWR9U9X0AyeL4ldlJ16A7LVXh-_-QqGnByIrpBFTc

### PR DESCRIPTION
**Pull request by ptrcarta**

### CODE REVIEW

**Comment by maran** [comment]
Good find! I will verify it when I'm on my macbook tomorrow morning.

**Comment by ecdsa** [comment]
why is emulate_argv=False needed?
I understand it fixes #1006, but do we understand why it fixes it?

**Comment by maran** [comment]
No we don't. I tried applying this patch but binary building is currently broken again with again the freaking CA_BUNDLE problem. `assert os.path.exists(requests.utils.DEFAULT_CA_BUNDLE_PATH)`

I don't have time to go into it right now I will check it again when I'm back from my holiday.

**Comment by ecdsa** [comment]
merging for now, but it would be better to find a proper fix

**Pull request merged**
