### PR TITLE
Add yadio.io api to exchange rate

### PR DESCRIPTION
**Pull request by Ventura94**
Added to API of yadio.io to obtain the free market price of the CUP (Cuban Peso)

### CODE REVIEW

**Comment by accumulator** [comment]
Please don't include reformatting of existing code, as this makes it tedious to review.

**Comment by Ventura94** [comment]
Please have my sincerest apologies. I'll keep it in mind for other collaborations. Can I do it again and fix it?

**Comment by accumulator** [comment]
> Please have my sincerest apologies. I'll keep it in mind for other collaborations. Can I do it again and fix it?

No apologies needed :) After you fix your patch, you can just force-push your branch and it will show up here.

**Comment by Ventura94** [comment]
I will do

**Comment by Ventura94** [comment]
I will do

**Comment by Ventura94** [comment]
@accumulator Ready

**Comment by accumulator** [comment]
A few tips: open source etiquette is to use the same indentation as the rest of the file, and in the case of resource lists like these exchange rate providers, to add your contribution to the end of the list (or at the appropriate spot if it's in alphabetical order).

You can also repair your previous commit by doing a `git commit --amend`, so you don't end up with two commits..
I took the liberty to combine the two commits and move the provider to the bottom.

Anyway, thanks for your contribution :)

**Pull request merged**
