### PR TITLE
initial fix for #2897

### PR DESCRIPTION
**Pull request by goblin**
This is my initial proposal for fixing #2897, which was closed prematurely IMO (please reopen until this is merged).

This allows offline-signing a transaction that was prepared using a watch-only address-based online wallet.

Generating the 40 addresses is a bit slow and this could surely be improved, but I'm not sure where the generated keys are stored -- and particularly how to access them from the Keystore. I'll be happy to fix this if you point me at the right direction.

I have successfully signed a testnet transaction using this patch (from 0th Receiving address), but this probably needs more testing than that. I'll be happy to have a look at how tests work too, if that's what you want.

### CODE REVIEW

**Comment by goblin** [comment]
No idea why the build failed. How do I run the tests on my box?

**Comment by bauerj** [comment]
That's unrelated to your PR.

**Comment by goblin** [comment]
I've rebased my fix onto the latest master

**Comment by ecdsa** [comment]
I disagree with that idea. If it is not possible to find the derivation in the general case, we should not try to do it for the first generated addresses. It is better to let users know right away that this combination does not work, instead of creating a system that will work for a while, and then inexplicably stops working.

**Comment by goblin** [comment]
OK, thanks for the explanation.

I believe it *is* possible to find it in the general case, with user input. It just needs to be presented slightly differently. Firstly, user would need to be aware which HD derivation the original address came from (so these would need to be displayed along with addresses, maybe in the Details view). Secondly, there'd need to be an option to enter that derivation in the Transaction Preview page. And presumably also having a button to "generate more derivations" would be useful too.

It's a bit more work, but I may consider doing it. If you really disagree with this (I do understand it's only usable for more advanced users), I guess I'll be keeping a fork.

**Comment by ecdsa** [comment]
I think it is better to educate users to do the right thing. 
maybe we can add that info in the wizard

**Comment by ecdsa** [comment]
but yes, I disagree with introducing complicated features when they can be avoided

**Comment by goblin** [comment]
So what's the right thing here to do for a user?

My use case is I prepare a lot of master HD keys offline. Then I export their first bitcoin address to a watch-only wallet. When I want to spend from an address, I prepare the transaction on an online watching-only wallet, and then want to be able to sign the transaction on an offline one.

So currently to do this, I need to create an intermediate wallet: either
1. on the offline machine, manually using the key from the HD wallet (and this is impossible to do with a key with ID greater than ~20), or
2. on the online one, by using the public part of the master HD key

Option 2. is better, and would actually work quite well if it was possible to import a lot of master public keys (rather than bitcoin addresses) to a watch-only wallet. I wouldn't need an intermediate wallet in this case.

So maybe that's the better way to go... What would you say to adding support for importing multiple master public keys in a watch-only wallet?

**Comment by ecdsa** [comment]
why can't you have several watching-only wallets?

**Comment by goblin** [comment]
@ecdsa I'm talking dozens, maybe even hundreds or master keys... it's impractical to have so many separate wallets

**Comment by ecdsa** [comment]
and you only watch one address per wallet?

**Comment by goblin** [comment]
Yes, however being able to watch more than 1 would also be nice. So implementing multiple xpubs per wallet would actually be even better for me than my original patch.

**Comment by ecdsa** [comment]
why don't you create two imported wallets, one with the addresses you want to watch, the other with the privkeys?

**Comment by goblin** [comment]
That's a good point. The reason in my case is security. I don't want the computer which signs the transaction to have access to any more private keys than necessary.

I generate the all the addresses on a computer which doesn't have any connectivity (not even via USB pendrives or such). I copy the required privkey (actually a wallet seed) via screen/keyboard to another offline one which then signs the transaction and stores it on USB.

**Comment by ecdsa** [comment]
well, in that case create many wallets with one privkey in each...

**Comment by goblin** [comment]
Yup, that's more or less what I'm doing. I could copy the private key over the screen/keyboard instead of a wallet seed.

But having a full HD wallet is more handy because it then allows to store change on a new address derived from the master key. Of course I now realize the online computer can't create such a transaction from just the bitcoin address, so it needs to know the xpub anyway.

I guess I'll just be copying over the xpub wallet when I want to spend from an address, but being able to import all of them at once to have in one window would be cool.

**Pull request closed without merging**
