### PR TITLE
Added ability to send to stealth addresses.

### PR DESCRIPTION
**Pull request by dabura667**
Currently unable to test more than 1 of 1 with no prefixes. As there is
no current wallet implementation with p2sh or prefixes to test with.

### CODE REVIEW

**Comment by dabura667** [comment]
Will re-open once Stealth is settled on.

It keeps having "its the last change" over and over again... so I'll wait til it is a BIP.
I will keep my branch up to date with the latest Dark Wallet version in case someone wants to use the commits.

**Comment by ABISprotocol** [comment]
@dabura667 Just curious, as this is closed, but did any of the work from this pull request get folded into something else electrum related?  Apart from [joinmarket](https://github.com/JoinMarket-Org/joinmarket/issues/549), what have been some ways that people have recently tried to explore addressing privacy issues with electrum?

**Comment by dabura667** [comment]
@ABISprotocol Unfortunately no. DarkWallet died. Stealth Address work died. The unSystem wiki (where all the work I had done on stealth) died.

Then BIP47 came out and myself included the whole community said "meh..."

That's basically the status right now.

**Comment by ABISprotocol** [comment]
@dabura667 Thanks for the update.  I have noticed that there was seemingly a temporary death of the unsystem mailing list, [but it came back](https://mailinglists.dyne.org/cgi-bin/mailman/listinfo/unsystem), and the [dyne site](https://dyne.org/) is alive and well, so that's good.

**Pull request closed without merging**
