### PR TITLE
add easy support for op return bytes

### PR DESCRIPTION
**Pull request by jcktm**
I need this for a token sale, feel free to merge. Not sure if ppl even want this feature but it would be super handy for me if it was  included in the next release ^_^

### CODE REVIEW

**Comment by jcktm** [comment]
Screen Shot 2019-06-09 at 12 40 08 am
Screen Shot 2019-06-09 at 12 40 58 am
Screen Shot 2019-06-09 at 12 40 35 am

**Comment by jcktm** [comment]
I guess it's not a good UX for non-technical folks though, so maybe the UI needs to change. Add a checkbox or something...

**Comment by SomberNight** [comment]
Thanks; but this functionality already exists :)
Clearly it's not advertised well enough.

You can already write stuff like this into the `Pay to` field:
```
tb1qmgfge5npg3cptmc06czl09altj4e4vx37clmdc, 0.001
OP_RETURN deadbeef, 0
OP_CHECKSIG 02b057b04a768053e450967fe75e2c3daacc38a2e9c3cd53f239beb3fc760b0614, 0.001
```
pr_5413

**Comment by jcktm** [comment]
Oh wow! Yeah I couldn't find it. This is great news, thanks!

**Pull request closed without merging**
