### PR TITLE
auto-remove paid invoices from GUI

### PR DESCRIPTION
**Pull request by ecdsa**
- delay 3 seconds in GUI
 - rename invoice lists to "send queue", "receive queue"
 - kivy remove 'delete' buttons from send/receive screens

### CODE REVIEW

**Comment by ecdsa** [comment]
note: `refresh_status` was needed to check for expiration of invoices

**Comment by SomberNight** [comment]
why is the 3 sec delay needed?

**Comment by ecdsa** [comment]
> why is the 3 sec delay needed?

the delay is there so that the transition to "paid" is visible for the user.
note that `update()` is currently called from from `update_tabs()`, this also needs to be fixed

**Comment by ecdsa** [comment]
Another issue is that we currently decide that an onchain invoice has been "paid", based on blockchain history. This obviously needs to be changed. I guess a popup question could be shown to the user in case of address reuse.

**Pull request merged**
