### PR TITLE
WIP: Trezor 0.11

### LINKED ISSUE #4806: OS X wallet import hardware ID issue
This one is a head scratcher but I'll do my best to describe how to reproduce.

Electrum 3.2.3 on testnet
OS X Sierra
Create 3-of-5 p2sh wrapped segwit wallet
First pubkey: import from Ledger Nano S with derivation path m/49/1/0
Second pubkey: import from Trezor One with derivation path m/49/1/0
Third pubkey: import from Trezor One with derivation path m/49/1/0
Fourth pubkey: import master upub
Fifth pubkey: import master ubpub

The problem occurs when importing the third pubkey (the second Trezor) - I unplug the first trezor immediately after importing its pubkey and plug in the second Trezor. Electrum says it detects a Trezor but it displays the label of the first Trezor rather than the second. If you proceed to import, it seems to import successfully. In fact, the wallet initializes as expected and even derives the correct addresses and finds transactions and balances.

The problem occurs when trying to spend from the wallet. You can successfully sign with the Ledger Nano S and the first Trezor, but then when trying to apply the third signature with the second Trezor, the operation fails because Electrum says it is expecting the first Trezor.

So it seems that the xpubs are all stored correctly, but something is stored incorrectly regarding the actual hardware device ID.

### PR DESCRIPTION
**Pull request by matejcik**
Posting this PR now for review. This works against unreleased python-trezor version 0.11.0, available from git master. There might be bugs.

Fixes:
- #4817
- #4404 (in case it wasn't resolved already)
- python-trezor update should resolve #4806
- #4083 due to rearchitecting the plugin
- #2440 and #3131 presumably gone
- ~~#4130 should be fixed in trezord 2.0.25~~

#4389 might still exist, albeit in a different form

Please wait with merge until 0.11.0 is released.

I also intend to improve outdated firmware detection.
Would you be OK with pinging our server on launch and checking for latest mandatory firmware update? If not, there is also going to be a hardcoded firmware version check in python-trezor.
(Alternately, I plan to implement something like `find_latest_firmware`, we could add a button to the settings dialog that would allow users to fetch latest firmware version.)

### CODE REVIEW

**Comment by SomberNight** [comment]
Nice list of fixes! :)

> Would you be OK with pinging our server on launch and checking for latest mandatory firmware update?

You mean this code would be in python-trezor?
In any case, no, please don't do this.

> If not, there is also going to be a hardcoded firmware version check in python-trezor.

Ok, sure. There is already a hardcoded fw version check in the plugin code though? But I guess you want more control over it (and enforce it for all users of python-trezor), so that's fine.

> Alternately, I plan to implement something like find_latest_firmware, we could add a button to the settings dialog that would allow users to fetch latest firmware version.

That's fine too, just don't connect to a central server silently by default.

**Comment by matejcik** [comment]
Understood.

The point of the new firmware checks is to enforce that people don't use old FWs with security problems, that's why I suggested auto-checking. python-trezor itself will not do silent pings. But I'll bundle latest-known-good FW images and check if yours is older than that.
As I intend to do it now, too-old firmware will raise exceptions by default. I'm thinking of making it possible to ignore them but having noisy warning boxes in the UI?

I'm also thinking that maybe opt-in checks would be OK? But implementing that is probably out of my current scope.
(also wondering if we could put firmware information on the blockchain so that you could check anonymously. But that's _really_ out of scope :)) )

**Comment by SomberNight** [comment]
> I'm also thinking that maybe opt-in checks would be OK? But implementing that is probably out of my current scope.
(also wondering if we could put firmware information on the blockchain so that you could check anonymously. But that's really out of scope :)) )

We're not even checking that the version of Electrum itself is up-to-date atm to avoid pinging a central server. These same points you mention came up re that. :P

> As I intend to do it now, too-old firmware will raise exceptions by default. I'm thinking of making it possible to ignore them but having noisy warning boxes in the UI?

I guess it's ~ok not to be able to ignore the error (I don't have a strong opinion), but the error should be displayed in the GUI and not crash the whole app of course.

**Comment by ecdsa** [comment]
hello, what is the ETA for trezor 0.11 ?

**Comment by matejcik** [comment]
@ecdsa most likely next week

**Comment by matejcik** [comment]
status update: python-trezor 0.11 is feature-complete, we're waiting to release it in sync with firmware 2.0.10

Obsolete firmware now raises UserFacingExceptions, which seems to do what we want:
- show device in "select device" list
- disallow creating wallets with it
- disallow any operations when an existing wallet is open

I had to remove the firmware check from `create_client` because then ... then the client would not get created, Electrum would think that there is nothing connected and do all sorts of special handling for "nothing is connected" state. It would be nice if "device exists but we don't want it" was a recognized state in itself.

in addition, turns out #4130 still exists

**Comment by ecdsa** [comment]
note: we probably need to replace client.py with trezor.py in the .spec files, for pyinstaller to include trezorlib

**Comment by matejcik** [comment]
@ecdsa won't it get pulled in through qt -> trezor -> clientbase ?

**Comment by matejcik** [comment]
python-trezor 0.11.0 is out \o/

Leaving the pyinstaller thing up to you, I have no idea how it's supposed to work.
But let me know if I can help

**Comment by ecdsa** [comment]
thanks! we will test it soon

**Comment by SomberNight** [comment]
Thank you for the PR; I think the code became clearer than it was before! :)

Somewhat related, I also pushed https://github.com/spesmilo/electrum/commit/8c3920a0db10d5519bc2435a5354c13aadb5ed1c to master, to improve the error msg the user sees.

**Pull request merged**
