### PR TITLE
test_mnemonic: add a test case for the new mnemonic module

### PR DESCRIPTION
**Pull request by romanz**

### CODE REVIEW

**Comment by ecdsa** [comment]
I cann see you were inspired by https://xkcd.com/221/

**Comment by romanz** [comment]
Indeed :)

**Comment by romanz** [comment]
@ecdsa , should I rewrite this test suite, by black-box testing `mnemonic.py`? 
(without adding a `randrange` keyword argument to `make_seed()` function)

**Comment by ecdsa** [comment]
yes that would be better...

**Comment by romanz** [comment]
100%

**Pull request closed without merging**
