### PR TITLE
Support for new hardware wallet: Coldcard

### PR DESCRIPTION
**Pull request by peter-conalgo**
Just a new hardware wallet plugin... for the Coldcard Wallet.

See <https://coldcardwallet.com> for more about the product.

### CODE REVIEW

**Comment by peter-conalgo** [comment]
_Some background info, taken from the README inside the PR:_

## Background

The Coldcard has a larger screen (128x64) and a number pad. For
this reason, all PIN code entry is done directly on the device.
Coldcard does not appear on the USB bus until unlocked with appropriate
PIN. Initial setup, and seed generation must be done offline.

Coldcard uses an emerging standard for unsigned tranasctions:

PSBT = Partially Signed Bitcoin Transaction = BIP174

However, this spec is still under heavy discussion and in flux. At
this point, the PSBT files generated will only be compatible with
Coldcard.

The Coldcard can be used 100% offline: it can generate a skeleton
Electrum wallet and save it to MicroSD card. Transport that file
to Electrum and it will fetch history, blockchain details and then
operate in "unpaired" mode.

Spending transactions can be saved to MicroSD using the "Export PSBT"
button on the transaction preview dialog (when this plugin is
owner of the wallet). That PSBT can be signed on the Coldcard
(again using MicroSD both ways). The result is a ready-to-transmit
bitcoin transaction, which can be transmitted using Tools > Load
Transaction > From File in Electrum or really any tool.

<https://coldcardwallet.com>

**Comment by SomberNight** [comment]
Hi. Can you give me an email address? Either here in the comments or e.g. send a mail to the email in my profile.

**Comment by peter-conalgo** [comment]
Now supports the latest PSBT file format, as defined in BIP-174.

**Comment by peter-conalgo** [comment]
Just a heads-up that I'm getting this back in sync with master right now.

**Comment by peter-conalgo** [comment]
Re: Testnet
- Yes, I use it on testnet most of the time (`./run_electrum --testnet`)
- To switch the Coldcard (uses the same seed) go to Settings -> Blockchain and make your choice. Change is immediate, but might be best to reboot/replug.

Re: p2wpkh works in the Coldcard firmware. Probably a derivation path problem. I'd like to look at that.

**Comment by peter-conalgo** [comment]
Re: Squash
- my git kung-fu is terrible; if you could do this for me, I'd appreciate it. Otherwise, I will be trolling thru google search results, and such...

Re: electrum-icons and electrum-locale
- I did not intend to change those, altho because this plugin introduces a new icon, it does affect the electrum-icons repo indirectly. I probably I captured the an updated submodule's hash accidentally.

**Comment by SomberNight** [comment]
Ok, I've figured out the p2wpkh thing; will fix.

> To switch the Coldcard (uses the same seed) go to Settings -> Blockchain and make your choice. 

Oh well... did not notice that :) I guess some of the stuff I did is harmful then; will undo parts

**Comment by SomberNight** [comment]
Ok, I've rebased and squashed.
I have a copy of the previous commits at https://github.com/spesmilo/electrum/compare/bc6010303a0010c9c027b99d8c65c68481d2c585...SomberNight:ckcc_before_rebase

**Pull request merged**
