### PR TITLE
Readme improvement: Added android-sdk to the apt-get installation instruction 

### PR DESCRIPTION
**Pull request by roth-a**
When following the Readme instruction I noticed that the android-sdk is necessary. Adding this to the Readme could make it easier for other readers.

### CODE REVIEW

**Comment by SomberNight** [comment]
For which step is it needed?
Or do you mean the `adb` invocations in the FAQ section?

**Comment by roth-a** [comment]
If remember correctly it was necessary for a successful dockers build of electrum. But I could test that again.

**Comment by SomberNight** [comment]
Well that sounds weird as the build happens inside the container, so whether something is installed outside it should be irrelevant.

**Comment by roth-a** [comment]
You are right. It is not needed. Sorry for the confusion.

**Pull request closed without merging**
