### PR TITLE
add ripemd test

### PR DESCRIPTION
**Pull request by cluelessperson**

### CODE REVIEW

**Comment by cluelessperson** [comment]
class name "Test_ripemd" is ugly.
So is "TestRipemd" :?

**Comment by bauerj** [comment]
Please remove these lines from the ripemd module then. No need to duplicate it.

**Comment by ecdsa** [comment]
I dont see the point of addding that test

**Comment by bauerj** [comment]
I do: It would be nice to know when future Python changes break this code. Arguable the code isn't changed that often but it's still good to know that it works.

What's the harm in merging this (once the code duplication is removed)?

**Comment by ecdsa** [comment]
this code is just not part of Electrum.

it is there only to provide ripemd hashing on Android because python-crytax does not have it.
it is not supposed to stay once python for android have fixed their hashlib module.

the harm merging that is that I get too many requests and that it takes too much of my time to evaluate them. adding requests of that kind is not productive at all. 

adding tests that actually test the software is difficult. it requires as much skills that writing the code itself.

**Pull request closed without merging**
