### PR TITLE
Update block explorer URL for btc.com

### PR DESCRIPTION
**Pull request by nachunjae**

### CODE REVIEW

**Comment by streetcrypto7** [comment]
@SomberNight  Can you merge this?

**Comment by SomberNight** [comment]
I recently tried to test this but btc.com did not load properly from two different IPs.
Does it load for you?

Further, what about the testnet btc.com a few lines below. Does that need to be changed?

**Comment by nachunjae** [comment]
@SomberNight I've removed testnet btc.com cause they've closed for testnets.

Mainnet BTC.com explorer works fine, Binance exchange use their exchange.

**Comment by SomberNight** [comment]
Ok. Well it still doesn't load for me but maybe they just rate limited all the proxies I have tried.

**Pull request merged**
