### PR TITLE
Build: create a .tar.xz archive

### PR DESCRIPTION
**Pull request by JeremyRand**
Fixes https://github.com/spesmilo/electrum/issues/4645

### CODE REVIEW

**Comment by SomberNight** [comment]
I get that xz compresses better than gz but is there really a point in having 3 distributables?
Can we maybe eliminate at least one of maybe even two of these?
Are there compatibility issues with some of these formats on some platforms?

**Comment by JeremyRand** [comment]
> I get that xz compresses better than gz but is there really a point in having 3 distributables?
> Can we maybe eliminate at least one of maybe even two of these?
> Are there compatibility issues with some of these formats on some platforms?

@SomberNight To the best of my knowledge, all recent GNU/Linux distros support all 3 (though I think `.zip` is a bad idea for GNU/Linux because it doesn't preserve all the permission metadata), and Windows only supports `.zip`.  So it's probably safe to remove `.tar.gz`.  I haven't verified this though, and I have no idea what the situation on macOS (or other more rare OS's) is.  Would you like me to remove `.tar.gz` as part of this PR?

**Comment by JeremyRand** [comment]
According to StackExchange macOS 10.9 and higher support `.tar.xz` natively.

**Comment by JeremyRand** [comment]
AFAICT, Debian Stretch KDE uses the `ark` package for decompressing stuff, which recommends `unar`, which supports both `gz` and `xz`.  So I think `.tar.xz` should be roughly the same as `.tar.gz` in terms of compatibility for GNU/Linux.

**Comment by JeremyRand** [comment]
I recently learned that the Ubuntu packaging team recommends that developers distribute source code tarballs as `.tar.gz`.  So, in order to make it easier for distro packagers' workflow, we probably shouldn't drop `.tar.gz`.  Mildly annoying having 3 archives, but probably doesn't do much harm.

**Comment by SomberNight** [comment]
Note: we stopped distributing `.zip` source archives in https://github.com/spesmilo/electrum/commit/c5c8ea15bbb2df18f9ac600a9f64bd43f05f81af, since it is difficult to build them reproducibly.

> I recently learned that the Ubuntu packaging team recommends that developers distribute source code tarballs as `.tar.gz`

I haven't tested reproducibility of `.tar.xz` sdists, but regardless, AFAICT the main advantage would be saving storage/bandwidth for users that download them, due to better compression. The size difference is <2x, with files in the 10 MB ballpark.
Not sure adding the extra format in addition to or replacing the current one (`tar.gz`) is worth it.

**Pull request closed without merging**
