### PR TITLE
Small blockchain.py changes

### PR DESCRIPTION
**Pull request by fanatid**
I make changes that describe in #1558 and something else.
@ecdsa not sure about project code style.. such as extra spaces for math operators */-+, if-else line..

### CODE REVIEW

**Comment by kyuupichan** [comment]
We're generally, other than line length (though even there I try to observe it), following PEP8 and so have spaces around binary operators.

**Comment by fanatid** [comment]
@kyuupichan thanks for answer, I re-read PEP8 for spaces around operators and change code. Hope that I made this in the right way.

**Comment by kyuupichan** [comment]
Thanks

**Comment by ecdsa** [comment]
please test before merging.. this code fails

**Comment by ecdsa** [comment]
fixed in f30149ad49f220da4639d897586345e7def531e4

**Pull request merged**
