### PR TITLE
patch for issue #955

### PR DESCRIPTION
**Pull request by Minthos**
Don't know why the line is there. Removing it seems to solve the problem.

### CODE REVIEW

**Comment by Minthos** [comment]
Testing shows that this fix only delays the problem.

**Comment by ecdsa** [comment]
that line is there because we don't want to create a wallet with watching thousands of addresses.
we only want to watch the addresses where we expect a payment.
to fix issue #955 correctly, we need to derive the address instead of calling wallet.get_address
I guess the semantics of wallet.get_address changed, and that caused the issue.

**Comment by Minthos** [comment]
Is there a function other than account.create_new_address(0) that will do what we want? If not, that seems to be the easiest solution.

**Comment by ecdsa** [comment]
I fixed #955 here: fb699e5294a48f12d32a5a9fb5eb5e847b10bbeb

**Comment by Minthos** [comment]
Ah, sweet.

**Pull request closed without merging**
