### PR TITLE
add lnurl-pay and lightning address support

### PR DESCRIPTION
**Pull request by bitromortac**
Open questions:
* Do we want to automatically resolve the lnurl/lightning address after pasting (privacy issue)?
* Lagging Lnurl request currently blocks GUI

Todo:
- [ ] Android send screen
- [ ] Better request error handling

### CODE REVIEW

**Comment by AugustoResende** [comment]
First issue: just solve LNURL through tor

**Comment by bitromortac** [comment]
> First issue: just solve LNURL through tor

If you configure a Tor proxy in the network settings that should do it already.

**Comment by Perlover** [comment]
Hello!

I tried to send to a Lightning Address (Electrum v 4.4.6) but I get the error:

```
Failed to parse 'Pay to' line:
lightning@address.here

Exception('invalid address or script.')
```

Is it bug or nor realized a Lightning Address supporting?

P.S. This electrum wallet has a lightning channels and can pay a lightning invoices...

**Comment by Perlover** [comment]
> Is it bug or nor realized a Lightning Address supporting?

I found that not realized:

["lightning address" support is postponed for now](https://github.com/spesmilo/electrum/pull/7839)

**Pull request closed without merging**
