### PR TITLE
SLIP-0039 wallet recovery

### PR DESCRIPTION
**Pull request by andrewkozlik**
Implements https://github.com/spesmilo/electrum/issues/5419.
Note that this PR does not include support for SLIP-0039 in the Kivy GUI.

### CODE REVIEW

**Review by DvalCaruso — COMMENTED** [review]
cool

**Comment by Davincible** [comment]
Why was this never picked up?

**Comment by prusnak** [comment]
@andrewkozlik can you please rebase?

**Comment by jonathancross** [comment]
@andrewkozlik please rebase again, thanks.

**Comment by prusnak** [comment]
There is no point in rebasing forever unless we know there is an interest to have this merged in. Is there? @ecdsa @SomberNight

**Comment by prusnak** [comment]
@ecdsa @SomberNight will you please have a look and provide feedback?

**Review by SomberNight — APPROVED** [review]
I've reviewed the changes except for `slip39.py` which I just glanced over.

Re `slip39.py`, given the json test vectors file passes, I trust it is correct. Also, thanks for adding test cases to `test_wallet_vertical.py`.

I wish the changes needed for `qt/seed_dialog.py` could somehow be encapsulated even more - but that does not seem easy.

There are some minor fixes I've pushed as a follow-up. In particular, not sure if it was deliberate but the UI allowed the user to enter an incorrect share and press "next" - I've changed this as I find it confusing.

Apologies for the delayed review. Thank you for the contribution.

**Comment by prusnak** [comment]
Thank you @SomberNight for the review and for the merge!

**Pull request merged**
