### PR TITLE
Electrum LTC 1.9.8.6

### PR DESCRIPTION
**Pull request by Zara2012**
Hi, I need your help . My wallet not received LTC. This program new for  me and I can't undersand way?
The wallet result clouse and written  " Not connected at server" Can you help me please
Tahnk you in advance Yulia

### CODE REVIEW

**Comment by dabura667** [comment]
Close this PR. Electrum does not offer support for forks.

**Comment by Zara2012** [comment]
were I can ask? my wallet dosn't work

**Comment by atweiden** [comment]
Open an issue here: https://github.com/pooler/electrum-ltc/issues

**Comment by dabura667** [comment]
by the way. Do not make a pull request unless you actually are contributing code.

Questions should be submitted as "issues".

**Pull request closed without merging**
