### PR TITLE
change coldcard icons to be more consistent with the other vendors

### PR DESCRIPTION
**Pull request by scgbckbone**

### CODE REVIEW

**Comment by nvk** [comment]
+1

**Comment by accumulator** [comment]
would be nice to add the svg too, for possible future use

**Comment by nvk** [comment]
Could make it happen, same 80x80px?

**Comment by accumulator** [comment]
svg is vector format, so dimensions shouldn't matter. Or did you make the image in a pixel editor?

**Comment by nvk** [comment]
Some editors need a pixel target for SVGs, doesn't mater at the end, but helpful.

**Comment by accumulator** [comment]
ah :) well 80px should be fine

**Comment by nvk** [comment]
I will make another PR

**Comment by nvk** [comment]
Here you go https://github.com/spesmilo/electrum/pull/7709

**Pull request merged**
