### PR TITLE
KeepKey Integration

### PR DESCRIPTION
**Pull request by dstanchfield**
Here is the KeepKey plugin based on Trezor's plugin (since device's are compatible).

Our python client must be installed https://github.com/keepkey/python-keepkey.  This is a modified version of Trezor's python client, adding support for KeepKey and the additional features KeepKey can do (for example our own version of device recovery that is more secure).

### CODE REVIEW

**Comment by ecdsa** [comment]
thanks! I will try it as soon as I get the sample

**Comment by ecdsa** [comment]
I am having the following error:
```
Traceback (most recent call last):
  File "/home/voegtlin/electrum/gui/qt/__init__.py", line 163, in run_wizard
    wallet = wizard.run(action, wallet_type)
  File "/home/voegtlin/electrum/gui/qt/installwizard.py", line 478, in run
    wallet.create_main_account(password)
  File "/home/voegtlin/electrum/plugins/keepkey.py", line 396, in create_main_account
    self.create_account('Main account', None) #name, empty password
  File "/home/voegtlin/electrum/lib/wallet.py", line 1712, in create_account
    account_id, xpub, _, _ = self.get_next_account(password)
  File "/home/voegtlin/electrum/lib/wallet.py", line 1696, in get_next_account
    xpub, xprv = self.derive_xkeys(self.root_name, derivation, password)
  File "/home/voegtlin/electrum/plugins/keepkey.py", line 414, in derive_xkeys
    xpub = self.get_public_key(derivation)
  File "/home/voegtlin/electrum/plugins/keepkey.py", line 418, in get_public_key
    address_n = self.plugin.get_client().expand_path(bip32_path)
  File "/home/voegtlin/electrum/plugins/keepkey.py", line 103, in get_client
    self.transport = HidTransport(d[0])
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.6.5-py2.7.egg/keepkeylib/transport_hid.py", line 26, in __init__
    super(HidTransport, self).__init__(device, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.6.5-py2.7.egg/keepkeylib/transport.py", line 14, in __init__
    self._open()
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.6.5-py2.7.egg/keepkeylib/transport_hid.py", line 90, in _open
    self.hid.open_path(self.device)
  File "hid.pyx", line 54, in hid.device.open_path (hid.c:1458)
IOError: open failed
```

dmesg gives the following:
```
[478827.335291] usb 2-1: new full-speed USB device number 69 using xhci_hcd
[478827.384157] usb 2-1: New USB device found, idVendor=2b24, idProduct=0001
[478827.384168] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[478827.384174] usb 2-1: Product: KeepKey
[478827.384179] usb 2-1: Manufacturer: KeepKey, LLC.
[478827.384184] usb 2-1: SerialNumber: 13831323511543036500B300
[478827.656580] hid-generic 0003:2B24:0001.0012: hiddev0,hidraw0: USB HID v1.11 Device [KeepKey, LLC. KeepKey] on usb-0000:03:00.0-1/input0
```

**Comment by ecdsa** [comment]
after a bit of googling, it looks like the same bug used to occur with trezor as well

**Comment by ecdsa** [comment]
and it's a permission problem.
with sudo I get "Device not initialized or passphrase request cancelled"
would be great to be able to initialize from the plugin

**Comment by ecdsa** [comment]
Please note that the plugins that define a new wallet type are no longer visible in the gui list of plugins. You need to create a button in the status bar, to launch your settings dialog. (see how I did it for trezor)

**Comment by ecdsa** [comment]
Another issue: Electrum hangs if I unplug KeepKey before I close Electrum

**Comment by dstanchfield** [comment]
Okay, I've added an icon/button for the status bar.  I also brought in the latest changes that were made to the Trezor plugin.  I also had to make a change to our client, so make sure that is updated before attempting to run this.

The client no longer hangs for me when you disconnect KeepKey.  But when you disconnect the KeepKey while Electrum is up, and reconnect, then try to interact with the device (for example change the Label), Electrum hangs.  This appears to be a problem too with the Trezor plugin.  I am still working on this one issue.

**Comment by ecdsa** [comment]
thanks! that was fast!

**Pull request merged**
