### PR TITLE
ElectroDoge

### PR DESCRIPTION
**Pull request by CryptoUnchained**
ElectroDogeu

### CODE REVIEW

**Review by CryptoUnchained — COMMENTED** [review]
🤙🏽

**Review by CryptoUnchained — COMMENTED** [review]
🤙🏽

**Review by CryptoUnchained — COMMENTED** [review]
Attempting fix to old Doge QT wallet dormant 8 years and needing upgrade on local fork and legacy bitcoin addresses needing to upgrade. Stuck between v 10 and 14.1 cannot merge due to bitcoin and ElectrumWallet deprecations

**Comment by SomberNight** [comment]
You are free to fork Electrum and adapt it to your altcoin. The license allows this.
However please do not pollute this repository with altcoins.

**Pull request closed without merging**
