### PR TITLE
add guide for hardware wallets

### PR DESCRIPTION
**Pull request by SomberNight**
"The following aims to be a concise guide of what you need to get your hardware wallet working with Electrum" (on linux)

see it rendered [here](https://github.com/SomberNight/electrum/blob/hw_wallet_guide/contrib/hw_wallet.md)

### CODE REVIEW

**Comment by bauerj** [comment]
Why don't you add this to https://github.com/spesmilo/electrum-docs?

**Comment by SomberNight** [comment]
oh good idea
was not sure where to put it to be honest

**Comment by SomberNight** [comment]
argh, those files are written in reStructuredText not Markdown :/
might do it a bit later then :)

**Comment by bauerj** [comment]
I added it to the docs repo.

**Comment by SomberNight** [comment]
:D thanks.

**Pull request closed without merging**
