### PR TITLE
BitBox02 v9.2.0: support for signing messages and for p2wsh-p2sh legacy multisig accounts

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by SomberNight** [comment]
Re the minimum library version bump, do you want to enforce it at runtime?
https://github.com/spesmilo/electrum/blob/83143f421a24559541ff9c7490ee7d5d541627bf/electrum/plugins/bitbox02/bitbox02.py#L602
I see there is a new field in one of the protobuf messages but I don't know how an old version library behaves when getting an extra field.

**Comment by benma** [comment]
> Re the minimum library version bump, do you want to enforce it at runtime?

Ah yes, thanks. I keep forgetting that this field exists :see_no_evil: Done.

I forgot to mention, in case you want to test it, here is the app to upgrade the firmware:

https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.23.0-rc1

Or if you want to flash it on the CLI using the Python tools, the firmware can be found here:
- BTC-only: https://github.com/digitalbitbox/bitbox02-firmware/releases/tag/firmware-btc-only%2Fv9.2.0
- Multi: https://github.com/digitalbitbox/bitbox02-firmware/releases/tag/firmware%2Fv9.2.0

**Comment by SomberNight** [comment]
I've tried signing a message using the Qt GUI, but it did not work:
```
E | gui.qt.main_window.[test_bitbox02_bip84] | on_error
Traceback (most recent call last):
  File "/home/user/wspace/electrum/electrum/gui/qt/util.py", line 840, in run
    result = task.task()
  File "/home/user/wspace/electrum/electrum/wallet.py", line 2041, in sign_message
    return self.keystore.sign_message(index, message, password)
  File "/home/user/wspace/electrum/electrum/plugins/bitbox02/bitbox02.py", line 596, in sign_message
    return client.sign_message(keypath, message.encode("utf-8"), xtype)
  File "/home/user/wspace/electrum/electrum/plugins/bitbox02/bitbox02.py", line 548, in sign_message
    _, _, signature = self.bitbox02_device.btc_sign_msg(
  File "/home/user/.local/lib/python3.8/site-packages/bitbox02/bitbox02/bitbox02.py", line 515, in btc_sign_msg
    sig = self._btc_msg_query(request, expected_response="sign_message").sign_message.signature
  File "/home/user/.local/lib/python3.8/site-packages/bitbox02/bitbox02/bitbox02.py", line 249, in _btc_msg_query
    btc_response = self._msg_query(request, expected_response="btc").btc
  File "/home/user/.local/lib/python3.8/site-packages/bitbox02/communication/bitbox_api_protocol.py", line 639, in _msg_query
    raise Bitbox02Exception(response.error.code, response.error.message)
bitbox02.communication.bitbox_api_protocol.Bitbox02Exception: error code: 101, message: invalid input
```

Also, after this exception, I think the device gets into an unusable state.
For example, until I unplug/replug it, this line will block forever:
https://github.com/digitalbitbox/bitbox02-firmware/blob/5b374230362eef16342c9f69ea5cf5e0fc81911e/py/bitbox02/bitbox02/communication/bitbox_api_protocol.py#L579

```
$ python3 -m pip show bitbox02
Name: bitbox02
Version: 5.0.0
```
firmware version 9.2.0

**Comment by benma** [comment]
@SomberNight Did you try mainnet or testnet? The bb02 only supports signing messages on mainnet.

As to the invalid state, if I try in testnet, I do get an error (expected), but I can continue using the device normally.

**Comment by SomberNight** [comment]
> Did you try mainnet or testnet? The bb02 only supports signing messages on mainnet.

Ok, I have tried with testnet. Indeed, mainnet seems to work

> As to the invalid state, if I try in testnet, I do get an error (expected), but I can continue using the device normally. Can you reliably reproduce this?

Hmm no actually, I cannot reproduce now -- it happened multiple times yesterday though :/ I have had to replug the device to get it to work - restarting Electrum was not enough. Could have been a VM quirk though, I was passing the device around between VMs. I am sure it happened because it made me spend time pinpointing exactly where it was hanging :)

**Pull request merged**
