### PR TITLE
Fix #9282

### LINKED ISSUE #9282: TypeError: bad operand type for abs(): 'NoneType'
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
Traceback (most recent call last):
  File "/tmp/.mount_electryqfzaJ/usr/lib/python3.10/site-packages/electrum/gui/qt/main_window.py", line 2195, in do_process_from_file
    self.show_transaction(tx)
  File "/tmp/.mount_electryqfzaJ/usr/lib/python3.10/site-packages/electrum/gui/qt/main_window.py", line 1109, in show_transaction
    show_transaction(tx, parent=self, external_keypairs=external_keypairs, payment_identifier=payment_identifier)
  File "/tmp/.mount_electryqfzaJ/usr/lib/python3.10/site-packages/electrum/gui/qt/transaction_dialog.py", line 420, in show_transaction
    d = TxDialog(
  File "/tmp/.mount_electryqfzaJ/usr/lib/python3.10/site-packages/electrum/gui/qt/transaction_dialog.py", line 565, in __init__
    self.update()
  File "/tmp/.mount_electryqfzaJ/usr/lib/python3.10/site-packages/electrum/gui/qt/transaction_dialog.py", line 909, in update
    invoice_amt = abs(amount) or self.tx.output_value()
TypeError: bad operand type for abs(): 'NoneType'

TypeError: bad operand type for abs(): 'NoneType'
```

Reporter
------------

This issue was reported by 9 user(s):

| Electrum Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 4.5.8  | 3.10.13 (main, Jun 28 2018, 19:01:02) [GCC 8.3.0] | Linux-6.8.0-47-generic-x86_64-with-glibc2.39 | standard | de_AT | [ℹ](https://crashhub.electrum.org//crash/34381) | 
| 4.5.8  | 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)] | macOS-15.0.1-x86_64-i386-64bit | standard | ? | [ℹ](https://crashhub.electrum.org//crash/34389) | 
| 4.5.8  | 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] | Windows-10-10.0.22631-SP0 | standard | en_US | [ℹ](https://crashhub.electrum.org//crash/34405) | 
| 4.5.8  | 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] | Windows-10-10.0.22631-SP0 | standard | en_US | [ℹ](https://crashhub.electrum.org//crash/34408) | 
| 4.5.8  | 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] | Windows-10-10.0.22631-SP0 | standard | en_US | [ℹ](https://crashhub.electrum.org//crash/34410) | 
| 4.5.8  | 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] | Windows-10-10.0.19045-SP0 | imported,standard | zh_CN | [ℹ](https://crashhub.electrum.org//crash/34419) | 
| 4.5.8  | 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] | Windows-10-10.0.19045-SP0 | standard,imported | en_GB | [ℹ](https://crashhub.electrum.org//crash/34426) | 
| 4.5.8  | 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] | Windows-10-10.0.19045-SP0 | standard,imported | en_GB | [ℹ](https://crashhub.electrum.org//crash/34427) | 
| 4.5.8  | 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] | Windows-10-10.0.19045-SP0 | standard | en_GB | [ℹ](https://crashhub.electrum.org//crash/34442) | 

Additional Information
------------------------

> cHNidP8BAHcCAAAAAegEF8HU1CZGr/uNxrPwY9t5RfH3d/IwN8ziq0IOAkdyAAAAAAD9////AuTIAgAAAAAAGXapFC+DSUpq5xpmYO+YV5JTMKsLQoWpiKwAG7cAAAAAABl2qRS/PDmbBvTE3MN/zxlc5ONujJumxYisOEANAAABAP0CAQEAAAABYJIDjNANClC3GfOpGIBVEEFs9oDnB0lebgQj+GazhTMMAAAAi0gwRQIhAO6IVmXFz3guAS8hPd4xKYnawTqaMigoacb8zPLr7OrVAiA5amGrdyKdk1GecnknNBp+bK6hcMjb/pKapWQKaD0EcgFBBPRcSl4GqWjYiwJYCjsdxBbRhktv5zgFPaX2WvLAR0QvJ3v8Vdcnb1JlHj790zaHKo6SwO8FGY0mpbL5nZwfB7P/////AqfouQAAAAAAGXapFM0bG4WPP7moeOMnecxaJpAYoJsfiKyztB8IAAAAABl2qRT5Qt0CchZF8VPYLHp8O96BzWJNOYisAAAAACIGAg72coICUXDGQGXOgyaTmQadH+AalVqRYqVdmZtdLJcnDEMjyEgAAAAAPwAAAAAiAgLeoyKl2MsDL9rxHeqjRYUjk/3oJ+kIvrgYr9j+qmY/ygxDI8hIAQAAAAIAAAAAIgICWe/tkxBK1RH2UGczYhvilwrJNChkWf0W3TG0GzXMbboMQyPISAAAAAALAAAAAA==

---

### PR DESCRIPTION
**Pull request by nhtb**
amount can be NoneType

### CODE REVIEW

**Comment by ecdsa** [comment]
thanks. note that you could make it simpler:
`invoice_amt = abs(amount) if amount else self.tx.output_value()`

**Comment by nhtb** [comment]
sure. but then this to be correct as amount may be 0 (not sure).
`invoice_amt = abs(amount) if amount is not None else self.tx.output_value()`

**Comment by ecdsa** [comment]
> sure. but then this to be correct as amount may be 0 (not sure). `invoice_amt = abs(amount) if amount is not None else self.tx.output_value()`

no, this does not work. it will return 0 if amount is zero, instead of self.tx.output_value()

**Comment by ecdsa** [comment]
fixed in a04844b451d69720385cf6965befb207e7b97e79

**Pull request closed without merging**
