### PR TITLE
Split tx dialog buttons

### PR DESCRIPTION
**Pull request by kyuupichan**
The "actions" (sign, broadcast, send to cosigner, verify GA instant)
go on the RHS next to the "Cancel" button.

Copy, QR code and save go on the left.

### CODE REVIEW

**Comment by kyuupichan** [comment]
Thomas - I think this is a slight improvement, as the action that the Cancel button refers to would now appear grouped with the Cancel button.   If there are no actions, the button just says Close.

The other 3 are left-aligned.

I recognize this is debatable so wanted your opinion / review.  Thanks.  This is the last of the TX dialog changes I planned.

**Comment by kyuupichan** [comment]
If you don't like them flush-left, we could put another spacer to the left, with a weight of e.g. 8

**Comment by ecdsa** [comment]
did you test this with  the cosigner pool plugin?

**Comment by kyuupichan** [comment]
I did.

**Pull request merged**
