### PR TITLE
iOS version

### PR DESCRIPTION
**Pull request by bauerj**
To do:

* Fix issue with SSL connections and aiorpcx

How to test:

1. Run `electrum/gui/ios/make_ios_project.sh` 
2. Open XCode project in `electrum/gui/ios/iOS` and add AVFoundation and libxml2.tbd

### CODE REVIEW

**Comment by cculianu** [comment]
You are a hero among men!

**Comment by ecdsa** [comment]
thanks.
I think it would make sense to move the non-python stuff to a separate repo

**Comment by bauerj** [comment]
I'm not sure, the XCode project is coupled to the Python code. E.g. if you changed the names of UI elements in Python, you would have to do the same change in the UI editor. It would make things harder to do changes in two separate repositories.

Having it all in a separate repository or merging it into this repository would be better than separating this PR IMO.

**Comment by cculianu** [comment]
Yeah.. the way it was made was basically with the assumption that ios/ lives within the Electrum dir.

Each time you generate the Xcode project for building on iOS, it actually pull in sources from ../electrum/* into the Xcode project's work directory.

It might be possible to rework this scheme actually.. I didn't spend too much time playing with how to trick the "Briefcase" system (which is what generates the project) or what options it has.

But yeah.. as of right now this thing is a bit awkward, I admit, in that it copies sources each time from ../electrum.. :/

Sorry! Python on iOS is super hard!

**Comment by cculianu** [comment]
Oh I see -- ecdsa wanted you to separate out the non-python bits from the python bits.

Yikes! That would make this already super non-obvious Python <--> ObjC coupling even more tedious to work with.  Ouch! :)

Nooo! 😱

**Comment by minkcrypto** [comment]
@bauerj @cculianu Any good news?

**Comment by akshaynexus** [comment]
Tested locally,gives the following errors on trying to run it in a simulator
```
Undefined symbols for architecture x86_64:
  "_xmlXPathEvalExpression", referenced from:
      -[RXMLElement childrenWithRootXPath:] in RXMLElement.o
  "_xmlXPathFreeObject", referenced from:
      -[RXMLElement childrenWithRootXPath:] in RXMLElement.o
  "_xmlXPathFreeContext", referenced from:
      -[RXMLElement childrenWithRootXPath:] in RXMLElement.o
  "_xmlStrcmp", referenced from:
      -[RXMLElement child:] in RXMLElement.o
      -[RXMLElement child:inNamespace:] in RXMLElement.o
      -[RXMLElement children:] in RXMLElement.o
      -[RXMLElement children:inNamespace:] in RXMLElement.o
      -[RXMLElement iterate:usingBlock:] in RXMLElement.o
  "_xmlGetNsProp", referenced from:
      -[RXMLElement attribute:inNamespace:] in RXMLElement.o
  "_xmlBufferFree", referenced from:
      -[RXMLElement xml] in RXMLElement.o
      -[RXMLElement innerXml] in RXMLElement.o
  "_xmlBufferCreate", referenced from:
      -[RXMLElement xml] in RXMLElement.o
      -[RXMLElement innerXml] in RXMLElement.o
  "_xmlGetProp", referenced from:
      -[RXMLElement attribute:] in RXMLElement.o
  "_xmlXPathNewContext", referenced from:
      -[RXMLElement childrenWithRootXPath:] in RXMLElement.o
  "_xmlBufferContent", referenced from:
      -[RXMLElement xml] in RXMLElement.o
      -[RXMLElement innerXml] in RXMLElement.o
  "_xmlDocGetRootElement", referenced from:
      -[RXMLElement initFromXMLData:] in RXMLElement.o
      -[RXMLElement initFromHTMLData:] in RXMLElement.o
  "_xmlNodeGetContent", referenced from:
      -[RXMLElement text] in RXMLElement.o
      -[RXMLElement innerXml] in RXMLElement.o
  "_xmlNodeDump", referenced from:
      -[RXMLElement xml] in RXMLElement.o
      -[RXMLElement innerXml] in RXMLElement.o
  "_xmlFree", referenced from:
      -[RXMLElement text] in RXMLElement.o
      -[RXMLElement innerXml] in RXMLElement.o
      -[RXMLElement attribute:] in RXMLElement.o
  "_xmlFreeDoc", referenced from:
      -[RXMLDocHolder dealloc] in RXMLElement.o
  "_htmlReadMemory", referenced from:
      -[RXMLElement initFromHTMLData:] in RXMLElement.o
  "_xmlReadMemory", referenced from:
      -[RXMLElement initFromXMLData:] in RXMLElement.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by akshaynexus** [comment]
the way i fixed it is by adding libxml2 to link binary with libraries section

**Comment by akshaynexus** [comment]
now having this problem
`2019-08-17 22:58:44.281996+0300 Electrum[6780:1815647] Unable to locate Electrum main module file.`

**Pull request closed without merging**
