### PR TITLE
Kivy installwizard back button fix2

### PR DESCRIPTION
**Pull request by zebra-lucky**
- kivy: dismiss previous wizard window on back button (additional fix on #5534)
- ~kivy: stop network on pause, save last wallet, start network on resume~

### CODE REVIEW

**Comment by ecdsa** [comment]
please note that network now has more jobs than self.fx.run: watchtower and jsonrpc
although these jobs are not wanted in the context of an android app, it would be cleaner to stop and restart the list of jobs.

**Comment by zebra-lucky** [comment]
What about the wallet?
I do minimal changes. Need to do more job on pause.

**Comment by zebra-lucky** [comment]
Changes in first commit dismiss current wizard page, when switching back.
Found current page is remains open (In `on_release` method current page is
closed by `close`/`dismiss`.

Second commit need to be revised. I Found after `on_pause`, `on_stop` is not called,
so possible situations when last working code in app is `on_pause`.
Maybe need add more code to write all changes to wallet.

About network part, Dash version saves additonal data on network stop,
so I added net stop/start.
And if app go in pause mode, it is logically to stop network, as timeouts will
happen on network connections after some time, and on resume reconnection
still need.

**Comment by zebra-lucky** [comment]
I can remove second commit and rebase code to current master, to simplify merge.

Other changes I need to revise and possibly make another PR

**Comment by zebra-lucky** [comment]
I've removed second commit and rebased code on current master branch.

> Do you have a way to trigger some weird behaviour that gets fixed by this change?
No, it`s not gave effects for me, only found by code review.

**Comment by zebra-lucky** [comment]
P.S.: I have small android practice and misunderstand pause mode. After reading docs and debugging I understand that only activity thread is paused, other threads continue to work, so need to stopping network in pause mode was a mistake.

**Comment by zebra-lucky** [comment]
P.P.S: But second problem is leaves. When on_pause is called and app is closed by UI (cross button), then on_stop is not called. So I added commit to save last wallet.

**Comment by SomberNight** [comment]
@ecdsa looking at https://github.com/spesmilo/electrum/commit/b6f63e1abf2cc3faa9c504e73af656889b9fab9e, this PR looks related :P

**Comment by ecdsa** [comment]
> @ecdsa looking at [b6f63e1](https://github.com/spesmilo/electrum/commit/b6f63e1abf2cc3faa9c504e73af656889b9fab9e), this PR looks related :P

Yes, it is just a pity that the OP was not able to properly explain what the issue was, it would have saved some time..
The bug was introduced in e953eebdb96e8657886e0daa3e7a8224c982cad5, where `on_keyboard` is added.

**Comment by ecdsa** [comment]
@zebra-lucky regarding the other commit in this PR, note that  `save_last_wallet` does not save the wallet file, it only saves the name of the last wallet in the config file. From your comments I supppose that you actually intended to save the wallet file.

**Pull request closed without merging**
