### PR TITLE
Fixed a missing import in exchange_rate.py that caused program hangs and...

### PR DESCRIPTION
**Pull request by chiguireitor**
... wallet corruption

Signed-off-by: John Miguel Villar Zavatti <johnvillarzavatti@gmail.com>

### CODE REVIEW

**Comment by ecdsa** [comment]
thanks. will set thread to daemon too

**Comment by chiguireitor** [comment]
Excellent... i saw that it was blocking user interaction with the frontend and that would help too

**Comment by ecdsa** [comment]
btw, what kind of wallet corruption did you experience? was it with git head code?

**Comment by ecdsa** [comment]
hmm, looks like you created your PR while running old code.
the "import SSLError" line was already there, now it is there twice..

**Comment by chiguireitor** [comment]
Weird.... i did a git pull and nothing came

**Comment by chiguireitor** [comment]
fuuuu.... i think i know what happened... i didn't update my repo here on github, forgot i forked it... crap

**Comment by ecdsa** [comment]
ok, reverted

**Comment by chiguireitor** [comment]
Thanks!.... i will find out how to pull latest head on the github interface

**Pull request merged**
