### PR TITLE
Test payment requests

### PR DESCRIPTION
**Pull request by MrNaif2018**
This PR adds basic regtest tests for payment request functionality. It tests 3 main things: request_status event is fired, getrequest returns correct status and tx_hashes includes the tx hash which paid the request

Note that it still doesn't catch the bug in #8113 because it requires a custom order of conditions to be tested, but at least this provides basic foundation for the existing functionality not to break

cc @SomberNight

### CODE REVIEW

**Comment by ecdsa** [comment]
Thanks for the PR
Is there a reason why you did this using regtest instead of unittest?
Regtest tests are expensive and slow. 
We try to use them only if inter process communication is needed.

**Comment by MrNaif2018** [comment]
Well, how else would I send payments without regtest funds? This test is actually quite fast when run as part of the suite (bootstrap in regtest is slow but it's already done)
The problem is that without such tests in the past there were bugs which weren't caught by unit tests. It tests the whole payment processing flow with electrum.

**Comment by ecdsa** [comment]
@SomberNight recently mentioned that he wants to add tests for invoices, not sure what kind of tests he had in mind

**Comment by MrNaif2018** [comment]
Yes, I've added them by his request. I am really interested in fixing #8113 ASAP, but it requires some core changes or maybe a wallet upgrade
P.S. I am currently online on IRC

**Comment by SomberNight** [comment]
I've added some unit tests in https://github.com/spesmilo/electrum/commit/7dcaa4b2049ee190ab9ff7a6518775955036c048.

**Comment by ecdsa** [comment]
closing in favor of unittests

**Pull request closed without merging**
