### PR TITLE
Add Hideez Wallet plugin

### PR DESCRIPTION
**Pull request by zebra-lucky**
- Add Hideez Wallet plugin

https://hideez.com/products/hideez-wallet
https://github.com/HideezGroup/python-hideez
https://pypi.org/project/hideez/

### CODE REVIEW

**Comment by zebra-lucky** [comment]
rebased to current master

**Comment by zebra-lucky** [comment]
Seen new Logger functionality, need to add changes.

**Comment by SomberNight** [comment]
Do you work for Hideez? Could you send me an email please?

**Comment by akhavr** [comment]
We're a 3 person team contracted to implement hideez support in Electrum.  Will email you tomorrow.

**Comment by zebra-lucky** [comment]
Rebased to current master.
Do I need to make rebse/squash also?

**Comment by zebra-lucky** [comment]
Rebased(squashed) to current master.

**Comment by akhavr** [comment]
Any updates here?

**Comment by ecdsa** [comment]
@akhavr can you send me your email address?

**Pull request closed without merging**
