### PR TITLE
Fix PEP8 warnings at lib/tests

### PR DESCRIPTION
**Pull request by romanz**
I would be happy to help making Electrum source code PEP8-compatible, starting from the tests.
I am trying to do the minimal amount of changes to make it pass PEP8 checker (#1048).

### CODE REVIEW

**Comment by romanz** [comment]
If it's OK, I would be happy to help to convert the rest of the code to PEP8.

**Comment by ecdsa** [comment]
I agree with most of the code formatting in PEP8, but breaking xpubs just to have shorter lines, seriously?

**Comment by ecdsa** [comment]
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by romanz** [comment]
100%, will fix.

**Comment by romanz** [comment]
I've added `# nopep8` remark at the end of lines containing xpub/xprv data.

**Comment by romanz** [comment]
BTW, is this PR still relevant?
If not, we can close it...

**Pull request closed without merging**
