### PR TITLE
Added BRL exchanges: Bitvalor, Foxbit, NegocieCoins

### PR DESCRIPTION
**Pull request by Marcdnd**
Could you please add this pull request, we added three new exchanges in the BRL market and updated the MercadoBitcoin link that was not working.

Sincerely,

Marcdnd

### CODE REVIEW

**Comment by ecdsa** [comment]
why are they all using the same bitvalor API ?

**Comment by ecdsa** [comment]
ok, seems legit.

**Comment by ecdsa** [comment]
still, they don't seem to have https. 
maybe it would be time to remove all sources that are not able to provide a https interface.

**Comment by Marcdnd** [comment]
HI!
The https link is not working, by the browser works but by the Electrum not, how to solve?
Bitvalor is a site where you add the prices of some Brazilian exchanges, you can check the link https: https://api.bitvalor.com/v1/ticker.json

May you help me?

Regards,

Marc

**Comment by ecdsa** [comment]
my browser shows 'insecure connection' on that link

**Comment by Marcdnd** [comment]
Your SSL certificate is expired, I'll get back to you to see if it works, thank you!

**Comment by lucaspersona** [comment]
The certificate has been updated now.

**Pull request merged**
