### PR TITLE
add SW wallets qt console password lock

### PR DESCRIPTION
**Pull request by zebra-lucky**
It is preferable to lock console on SW wallets with keystore encryption

### CODE REVIEW

**Comment by SomberNight** [comment]
Why do you think this is needed?

**Comment by zebra-lucky** [comment]
If wallet leaved open, someone else can get aceess to sensitive info.

**Comment by SomberNight** [comment]
Such as? Ciphertext of seed words? Some examples might be nice.
Much privacy compromising info is already accessible in such a scenario without using the console; such as your xpub.

**Comment by zebra-lucky** [comment]
GC sometime can have xprv.

**Comment by zebra-lucky** [comment]
I'm sorry, it was possible false about xpriv, trying to find again and noting was found.
But in garbage collector there is huge amount of data, maybe somethen else can be found.

**Comment by ecdsa** [comment]
this is the wrong approach.
if private keys remain in memory after they have been used, then we should clear them.
building a fence around the python console is not going to make things safer

**Comment by zebra-lucky** [comment]
About a false positive: I'm switching password on-off and make a dump in a file.
Now seems that xprv was from a paswordless variant, so xprv does not remains in gc.
Maybe some data from qt widgets can be found, not sure about it.

**Comment by zebra-lucky** [comment]
found a bug, when console is not show in menu, widget is displayes, will add fix today

**Comment by SomberNight** [comment]
If there is secret material in memory left uncleared, that is e.g. accessible from the console, we should try our best to fix that and clear it, as said already in the thread.

The solution proposed here feels hackish. Not in implementation but in idea. Putting a Qt widget on top of the console only protects against a very limited set of attack vectors, namely the scenario where the wallet owner left Electrum running with a wallet open, they left the OS unlocked, and an attacker gains complete control of the OS (by e.g. physically controlling the mouse/keyboard).

If someone physically accesses your computer, they might just dump the memory of the python process.

**Pull request closed without merging**
