### PR TITLE
Trezor: support for Shamir backup and recovery

### PR DESCRIPTION
**Pull request by matejcik**
implements #5418

please let me know if there's a code style tool I should be using?

### CODE REVIEW

**Comment by matejcik** [comment]
rebased and retriggered CI check (which seemed to failed for unrelated reasons before).

**Comment by SomberNight** [comment]
Do you really want Shamir to be the default if it's available?

**Comment by SomberNight** [comment]
Otherwise, the diff itself look okay. :)

One concern I have is that if a user generates a Shamir backup on their Trezor, and they lose their device, they currently can't restore from the backup in software. This is part of the reason I am thinking Shamir should not be default for now.

**Comment by matejcik** [comment]
you are right, we decided to keep the default the same as the current Wallet, even if Shamir is available.

> One concern I have is that if a user generates a Shamir backup on their Trezor, and they lose their device, they currently can't restore from the backup in software.

also true, and #5419 is still far on the roadmap, at least from my side.

made the change and rebased on top of today's master

**Comment by SomberNight** [comment]
I've discussed with @ecdsa, and we think until it is implemented to restore from backup in software (without hw device), the Shamir options should be less visible.

In https://github.com/spesmilo/electrum/pull/5692/commits/18209fc782c08bb4b41d878d8fdedce86d9fa309, I've made these only visible after the user clicks "expert settings".

After https://github.com/spesmilo/electrum/issues/5419, we can make them more visible or even the default.

**Comment by SomberNight** [comment]
Thank you for your work.

**Pull request merged**
