### PR TITLE
Add audio modem integration for transaction sending & receiving

### PR DESCRIPTION
**Pull request by romanz**
This allows air-gapped transfer of transactions between a watching-only online wallet and an offline wallet, holding the private keys.

The two additional icons are:

 - http://www.flaticon.com/free-icon/speaker-outline_54951,
made by <a href="http://catalinfertu.com">Catalin Fertu</a> 
from <a href="http://www.flaticon.com">www.flaticon.com</a> is licensed under 
<a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a>.

- http://www.flaticon.com/free-icon/mic_10032,
made by <a href="http://www.elegantthemes.com">Elegant Themes</a> 
from <a href="http://www.flaticon.com">www.flaticon.com</a> is licensed under 
<a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.

### CODE REVIEW

**Comment by ecdsa** [comment]
I'm experiencing difficulties installing pyaudio.
it seems too unstable

**Comment by romanz** [comment]
Using 'pip install pyaudio' did not work for me, so I have used 'apt-get
install python-pyaudio' on Linux Mint 17, and worked OK. On Windows, I have
used the binary installer from pyaudio homepage.

I would be happy to help with the installation issues.

**Comment by romanz** [comment]
BTW, if pyaudio is problematic, I can drop it and use PortAudio directly
via ctypes.

**Comment by romanz** [comment]
May be using https://github.com/elijahr/portaudio-ctypes can help.

**Comment by romanz** [comment]
I have remove `pyaudio` requirement by using PortAudio API directly.
Tested on Linux Mint 17, after isntalling `portaudio19-dev` package.

**Comment by ecdsa** [comment]
thanks for removing the dependency.
I tested and got this: 
```
Traceback (most recent call last):
  File "/home/voegtlin/electrum/plugins/audio_modem.py", line 119, in sender_thread
    with self._audio_interface() as interface:
  File "build/bdist.linux-x86_64/egg/amodem/audio.py", line 27, in __enter__
    self.call('Initialize')
  File "build/bdist.linux-x86_64/egg/amodem/audio.py", line 20, in call
    return func(*args)
  File "build/bdist.linux-x86_64/egg/amodem/audio.py", line 24, in _error_check
    raise Exception(res, self._error_string(res))
Exception: (-10000, 'Host error.')

```

**Comment by romanz** [comment]
Hmmm... could you please tell me your Linux distro? 
I can try to boot it in a VM, to investigate the problem.

```
$ python -c "from platform import *; print(platform(), python_version(), uname())"
```

**Comment by romanz** [comment]
Could you please also run the following test on the latest `amodem` package (from https://github.com/romanz/amodem/commit/4dd2ef994eef99f693030ab08dd3a2e5611b5b1c):
```
import amodem
import logging

logging.basicConfig(level=0, format='%(asctime)s %(levelname)-10s '
                                    '%(message)-100s '
                                    '%(filename)s:%(lineno)d')
amodem.log.setLevel(amodem.logging.DEBUG)

interface = amodem.audio.Interface(config=amodem.config.fastest(), name='libportaudio.so')
with interface:
    r = interface.recorder()
    data = r.read(64000)  # record 2 seconds of audio

    p = interface.player()
    p.write(data * 5)    # play it back several time
```

On my Linux, it outputs:
```
$ python test_audio.py 
2015-01-06 22:25:03,155 DEBUG      API call: GetVersion()                                                                               audio.py:21
2015-01-06 22:25:03,155 DEBUG      API call: GetVersionText()                                                                           audio.py:21
2015-01-06 22:25:03,155 DEBUG      Library version #1899: PortAudio V19-devel (built Feb 25 2014 21:09:53)                              audio.py:14
2015-01-06 22:25:03,155 DEBUG      API call: GetErrorText(0,)                                                                           audio.py:21
2015-01-06 22:25:03,156 DEBUG      API call: Initialize()                                                                               audio.py:21
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
2015-01-06 22:25:03,213 DEBUG      API call: GetDefaultInputDevice()                                                                    audio.py:21
2015-01-06 22:25:03,214 DEBUG      API call: OpenStream(<cparam 'P' (0x7fd3f6005760)>, <cparam 'P' (0x1b2d570)>, None, c_double(32000.0), c_ulong(4096L), c_ulong(0L), c_void_p(None), c_void_p(None)) audio.py:21
2015-01-06 22:25:03,216 DEBUG      API call: StartStream(<amodem.audio.LP_c_void_p object at 0x7fd3f6005710>,)                          audio.py:21
2015-01-06 22:25:03,219 DEBUG      API call: ReadStream(<amodem.audio.LP_c_void_p object at 0x7fd3f6005710>, <ctypes.c_char_Array_64000 object at 0x7fd3f60059e0>, c_ulong(32000L)) audio.py:21
2015-01-06 22:25:04,261 DEBUG      API call: GetDefaultInputDevice()                                                                    audio.py:21
2015-01-06 22:25:04,261 DEBUG      API call: OpenStream(<cparam 'P' (0x7fd3f6005ac0)>, None, <cparam 'P' (0x1b600e0)>, c_double(32000.0), c_ulong(4096L), c_ulong(0L), c_void_p(None), c_void_p(None)) audio.py:21
2015-01-06 22:25:04,304 DEBUG      API call: StartStream(<amodem.audio.LP_c_void_p object at 0x7fd3f6005a70>,)                          audio.py:21
2015-01-06 22:25:04,307 DEBUG      API call: WriteStream(<amodem.audio.LP_c_void_p object at 0x7fd3f6005a70>, c_char_p(140548317995060), c_ulong(160000L)) audio.py:21
2015-01-06 22:25:08,800 DEBUG      API call: StopStream(<amodem.audio.LP_c_void_p object at 0x7fd3f6005710>,)                           audio.py:21
2015-01-06 22:25:08,801 DEBUG      API call: CloseStream(<amodem.audio.LP_c_void_p object at 0x7fd3f6005710>,)                          audio.py:21
2015-01-06 22:25:08,803 DEBUG      API call: StopStream(<amodem.audio.LP_c_void_p object at 0x7fd3f6005a70>,)                           audio.py:21
2015-01-06 22:25:08,806 DEBUG      API call: CloseStream(<amodem.audio.LP_c_void_p object at 0x7fd3f6005a70>,)                          audio.py:21
2015-01-06 22:25:08,807 DEBUG      API call: Terminate() 
```

**Comment by romanz** [comment]
BTW, which `portaudio` package are you using?

Mine is:
```
$ dpkg -s portaudio19-dev 
Package: portaudio19-dev
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 603
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: portaudio19
Version: 19+svn20140130-1
Replaces: libportaudio-19-dev, libportaudio19-dev
Depends: libasound2-dev, libjack-dev, libportaudio2 (= 19+svn20140130-1), libportaudiocpp0 (= 19+svn20140130-1)
Suggests: portaudio19-doc
Conflicts: libportaudio-19-dev, libportaudio-dev, libportaudio19-dev
Description: Portable audio I/O - development files
 PortAudio is a portable audio I/O library designed for cross-platform
 support of audio. It uses a callback mechanism to request audio
 processing.  Audio can be generated in various formats, including 32
 bit floating point, and will be converted to the native format
 internally.
 .
 This package contains the development files.
Original-Maintainer: Debian VoIP Team <pkg-voip-maintainers@lists.alioth.debian.org>
Homepage: http://www.portaudio.com/
```

**Comment by romanz** [comment]
BTW, which `portaudio` package are you using?

Mine is:
```
$ dpkg -s portaudio19-dev 
Package: portaudio19-dev
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 603
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: portaudio19
Version: 19+svn20140130-1
Replaces: libportaudio-19-dev, libportaudio19-dev
Depends: libasound2-dev, libjack-dev, libportaudio2 (= 19+svn20140130-1), libportaudiocpp0 (= 19+svn20140130-1)
Suggests: portaudio19-doc
Conflicts: libportaudio-19-dev, libportaudio-dev, libportaudio19-dev
Description: Portable audio I/O - development files
 PortAudio is a portable audio I/O library designed for cross-platform
 support of audio. It uses a callback mechanism to request audio
 processing.  Audio can be generated in various formats, including 32
 bit floating point, and will be converted to the native format
 internally.
 .
 This package contains the development files.
Original-Maintainer: Debian VoIP Team <pkg-voip-maintainers@lists.alioth.debian.org>
Homepage: http://www.portaudio.com/
```

**Comment by ecdsa** [comment]
I use ubuntu 14.04
it refused to install portaudio19-dev until I forced the installation of libjack0
besides that, the plugin works.

**Comment by ecdsa** [comment]
merged manually. I changed the auto-enable behaviour.

**Comment by ecdsa** [comment]
note: `import amodem` requires 120 ms on my laptop.
maybe it could be optimized?

**Comment by romanz** [comment]
Thanks a lot for merging this plugin!

Regarding the import times - the first run takes a while indeed (on my PC it was ~180ms).
The following execution was much faster (~45ms), probably due to good caching.

I've used the following code to profile the import statements, and I believe that most (~90%) of the time is spent importing `numpy` package:
```
import time
t = time.time()
try:
    print_msg('start', time.time() - t)
    import numpy
    print_msg('numpy', time.time() - t)
    import amodem.audio
    print_msg('audio', time.time() - t)
    import amodem.config
    print_msg('config', time.time() - t)
    import amodem.recv
    print_msg('recv', time.time() - t)
    import amodem.send
    print_msg('send', time.time() - t)
    print_msg('Audio MODEM is available.')
    amodem.log.addHandler(amodem.logging.StreamHandler(sys.stderr))
    amodem.log.setLevel(amodem.logging.INFO)
    print_msg('logs', time.time() - t)
except ImportError:
    amodem = None
    print_msg('Audio MODEM is not found.')
```

And got the following results:
```
$ ./electrum -o -v 
electrum directory /home/roman/.electrum
start 0.0
numpy 0.0418348312378
audio 0.0422189235687
config 0.0434348583221
recv 0.0451748371124
send 0.0453259944916
Audio MODEM is available.
logs 0.0453968048096
wallet path /home/roman/.electrum/wallets/default_wallet
```

**Pull request merged**
