### PR TITLE
Print exceptions to the built-in console

### PR DESCRIPTION
**Pull request by bauerj**
Closes: #2009

### CODE REVIEW

**Comment by ecdsa** [comment]
that's not going to prevent the gui from crashing.
I'll try to find another solution

**Comment by bauerj** [comment]
I don't understand. How should it prevent the GUI from crashing?

**Comment by ecdsa** [comment]
if there is a crash that crashes the gui, you will not see it in the console with that hook. you will just keep crashing. I think maybe the whole gui execution should be in a try..except block, and SimpleConfig instanciation should be deferred to the GUI.

**Comment by bauerj** [comment]
Indeed, it also doesn't log any exceptions that occur before the GUI is opened.

However, I don't see how catching the exception outside of the GUI would solve that.

**Comment by ecdsa** [comment]
well, that means we would not print the exception in the console, but we would open a popup window after the gui has crashed. maybe it can be done by sys.excepthook, not sure.

**Comment by bauerj** [comment]
I'm not sure if e.g. exceptions in background threads can be caught when initializing the GUI and those should probably be logged too.

**Pull request closed without merging**
