### PR TITLE
Allow users to specify lock_time for transactions

### PR DESCRIPTION
**Pull request by bauerj**
To do:
====
* [X] Add date-time picker to Send tab
* [X] Add timestamp to the transaction
* [x] Set sequence to `MAX-1` in order to enable the lock
* [x] Clarify the "lock time" entry in the preview window (Add "Block" for blocks and readable time for time)
* [x] Disable broadcasting if the lock time is in the future

Anything else?

Screenshots:
====
python_2017-05-14_20-23-40
python_2017-05-14_20-23-44
python_2017-05-14_22-15-19
python_2017-05-14_22-15-26

Closes: #1685
See: https://en.bitcoin.it/wiki/Protocol_documentation#tx

cc: @ulrichard @Rspigler

### CODE REVIEW

**Comment by bauerj** [comment]
Regarding the need to enable RBF: I was able to broadcast a [timelocked transaction](http://tbtc.blockr.io/tx/info/e6e9367f45240b273df7c361290a3e83fe43311efbd29771591537674f57bcd9) with RBF disabled but unable to do so with RBF enabled. So it looks like the documentation is right on this one.

**Comment by ecdsa** [comment]
I don't understand; do you need to enable or to disable RBF?

**Comment by bauerj** [comment]
For a timelocked transaction that's not valid yet:

- with RBF disabled: accepted by the network
- with RBF enabled: rejected by the network

So RBF needs to be enabled for the lock to work.

**Comment by ecdsa** [comment]
I used your locktime fix in d4e8f4beb630d46cdc196df11dcf57540f0bec71

I am not merging the rest of this PR, because I think this should not be part of the wallet, as long as the wallet does not have unbroadcasted transaction in its history. As it is now, the wallet will create transactions that are immediately double spent the next time you use the wallet. That is too confusing.

I plan to add support for unbroadcasted transactions, though.

**Comment by dabura667** [comment]
You don't need to activate RBF.

The nSequence needs to be < 0xffffffff and RBF flag is < 0xfeffffff (little endian) so just make the nSequence be (2**32)-2 ( == 0xfeffffff)

**Comment by bauerj** [comment]
Yes, that's what I did in bauerj/electrum@4157fc2976a5a84d981c602143c19c650314d947

**Comment by Rspigler** [comment]
Hello,

I apologize for my late response.  @bauerj , as you likely saw in (https://github.com/spesmilo/electrum/issues/2401), I had placed a $200 bounty on this feature.  Although @ecdsa did not pull the code, it seems you did do all the work necessary on a very nice implementation, and that there are plans to possibly allow this feature in the future.

Can you either:

A)  Post and sign a bitcoin address you would like me to send the funds to (so that the community may verify that I have kept my word), or

B)  If you would like to keep this address private, please send the address to my email, and encrypted with my public key.  Once you have received a satisfactory number of confirmations, please post a signed message here stating that the transaction has been completed, so once again the community may confirm.

Thank you,

Robert

**Comment by bauerj** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I don't think this will be merged. The reasoning was that this use-case isn't common enough to confuse users with this option.

However, if you still want to send me the coins, you can send them to 13U9U1wzUnJHbztsnkZiXdi1Qi65DtDLUV which is also the address associated with my keybase account: https://keybase.io/bauerj
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJZMTlpAAoJEITxv5JbH0hNZ/oH/jtbNKgzVWs2TJ0spMs0Mmbv
oSR+DQ4D6xFWpa+GHphr1CqAcW8/eYX4ybc5EDgEX8ocOnmHh7e8GxrloKuIpAq8
NgkAhW6FF5pGtFhzDruSp+L9E9/C8nBqTnJ+4pO5sLXadHAAz+3bMn9PUmyEJOqs
OEm3ZyZEC4QMlPm1DawGx/ZZB+zierwiWVWHDXkfYAoRAUW/K83RgXZLPKw36MiI
63HHjdSJIaocNYPBFEReFREFbCAQ3ljXMs6PsGOMALYHteVvDWYWs3S29gImmN0F
ZTZs73NvGr5D5lBBbwTIii6RDgtkkKWoMLZ5GCEvkEyLNWLQz8ojhlv03FB73/k=
=gp/G
-----END PGP SIGNATURE-----

**Comment by Rspigler** [comment]
Hi @bauerj, I believe you've earned the full bounty regardless, but I do greatly appreciate your candor.

The transaction can be seen here:  https://btc.blockr.io/tx/info/2f9e763141efaa405dccfa4d5b9ea8ec5c9e5eae02d081917e3f20df67a2e05b

Robert

**Comment by Robot1982** [comment]
> I used your locktime fix in [d4e8f4b](https://github.com/spesmilo/electrum/commit/d4e8f4beb630d46cdc196df11dcf57540f0bec71)
> 
> I am not merging the rest of this PR, because I think this should not be part of the wallet, as long as the wallet does not have unbroadcasted transaction in its history. As it is now, the wallet will create transactions that are immediately double spent the next time you use the wallet. That is too confusing.
> 
> I plan to add support for unbroadcasted transactions, though.

How about e726752 (Clarify the "lock time" entry in the preview window). This is useful when you load time locked transactions and you want to sign them with electrum (cold storage). It confirms that the time lock you want is correct (especially if it is a date (> 500000000)). This is useful even if the rest of the PR is not being merged.

**Comment by ecdsa** [comment]
note: Electrum now supports local transactions, so maybe we should reopen this

**Comment by roth-a** [comment]
Pro:
I like this very advanced option, and a nice to have feature. However I think there should be some feature test with testnet or regtest, to make sure the code actually works as intended. Reasoning:
It is harder to check if the network accepts the transactio,  than without locktime, because it is dependent on time or blockheight.


Con:
People, believing there is no immediate risk, store this transaction on Google drive. They of course forget the due date, and when they check they discover that the funds are gone.

**Comment by Robot1982** [comment]
> Con:
> It could create a false sense of security. Example:
> People, believing there is no immediate risk, store this transaction on Google drive. They of course forget the due date, and when they check they discover that the funds are gone.

Maybe this should be enabled only if the "Advanced preview" is enabled (new feature in 4.0.0)? By doing so it will not confuse inexperienced users, but it will still be available for the more advanced users. I think this is a good compromise.

**Comment by SomberNight** [comment]
Yes, in the new Preview dialog, just like RBF can be toggled directly in the dialog, the locktime could also be made customisable (it's shown already anyway).
Further, unlike when this PR was opened, the wallet now allows saving "local" transactions into its history. This seems ideal for future-timelocked txns, as now they can be saved into the wallet itself, and further, in this case, the affected UTXOs will not be "mistakenly" double-spent (invalidating the future-timelocked txn).

**Comment by patchmaster** [comment]
I love this feature. For now I have ported the patch to electrum-3.3.8 and it works for legacy addresses. I don't think it works for segwit though. https://pastebin.com/XEf4XLbp
I would love the option to generate also tx based on the timelocked utxo, knowing that the new tx would be accepted by the network only after a successful acceptance of the timelocked one.

**Pull request closed without merging**
