### PR TITLE
Add JPY exchange rate

### PR DESCRIPTION
**Pull request by wakiyamap**
I added three major Japanese exchanges.
BitFlyer https://bitflyer.jp/
BitBank https://bitbank.cc/
Zaif https://zaif.jp/

### CODE REVIEW

**Comment by dabura667** [comment]
ACK

**Comment by ecdsa** [comment]
reverted in 1c0e23c8b90a99f7a2fe1b8e2dbbd128fa1c7d5f
please fix

**Comment by wakiyamap** [comment]
@ecdsa 
Sorry.
What do I fix ?

**Comment by ecdsa** [comment]
it crashes the preferences dialog

**Pull request merged**
