### PR TITLE
Add the "Opendime Helper" plugin for Electrum (take 3)

### PR DESCRIPTION
**Pull request by peter-conalgo**
- same code, but against new master
- includes code from PR #1888 (fail if fee exceeds amount during sweep)

### CODE REVIEW

**Comment by peter-conalgo** [comment]
sorry guys; I didn't test this at all.... standby for fixes.

**Comment by peter-conalgo** [comment]
Those travis errors have to do with unrelated changes to wallet code (not my stuff). I think this code is good to merge right now.

**Comment by ecdsa** [comment]
don't worry about the travis errors, they are not related to your PR

**Comment by ecdsa** [comment]
I was able to initialize a device (index.html shows a Bitcoin payment address)
unfortunately the plugin fails to detect it ("no units found" message)

**Comment by peter-conalgo** [comment]
Ok, questions:
1) did your O/S remount the Opendime okay?
2) what path was it (re)mounted on?
3) do you have `libusb2` and/or `psutil` installed? (check OD plugin settings page to know)

I haven't tested this code on anything but Mac OS at this point, so that may be a factor...

**Comment by ecdsa** [comment]
1. yes
2. it is mounted on /media/<username>/OPENDIME
3. no, psutil was not installed. 

After installing psutil, it detects the dongle. However the status of the dongle "INVALID". the contextual menu says "os.statvfs didnt show correct disk geometry". I have no idea what it means.

Notes:
 - the plugin's is_available() method should return False if dependencies are not met.
 - the context menu cannot be removed by pressing, the escape key, it requires the mouse
 - when removing the dongle, I get this error: 
```
Traceback (most recent call last):
  File "/opt/electrum/plugins/opendime/qt.py", line 619, in on_scan_done
    self.od_wallet.delete_imported_key(item.unit.address)
AttributeError: 'OpendimeTransientWallet' object has no attribute 'delete_imported_key'
```

**Comment by peter-conalgo** [comment]
Looks like you are using Linux, and I have some more work to do. I'll try to clear this up by end of next week.

**Comment by bauerj** [comment]
@peter-conalgo Any progress on this?

**Comment by nvk** [comment]
Feel free to close this pull.

**Comment by bauerj** [comment]
@nvk Why?

**Comment by nvk** [comment]
This pull is too old, we will just make a new PR in the future.

**Pull request closed without merging**
