### PR TITLE
tx dialog: show various warnings if input amounts cannot be verified

### LINKED ISSUE #5749: Warning on signing non-segwit input
The [current warning text](https://github.com/spesmilo/electrum/blob/7b18c91b74bbebfe56ba547080ab29775e42feb2/electrum/gui/qt/transaction_dialog.py#L486) only mentioned the risk of paying higher mining fee than expectation. However, to my understanding, the actual risk seems to be higher than that: 

Under a scenario that a payment involves multiple parties. a malicious party could stealthily replace their own inputs with UTXOs of lower value, while the victims' inputs would be replaced with UTXOs of (corresponding) higher value, thus the victims would actually pay a (much) higher amount than expectation during this payment.

Edit 2020-06-05: After learning the details of the recently-disclosed [security issue of BIP143](https://github.com/spesmilo/electrum/pull/6198), I have realized it's not the UTXOs would be replaced, but the amounts would be directly tampered by the attacker.

### PR DESCRIPTION
**Pull request by SomberNight**
closes #5749

These warning texts are really hard to write...

### CODE REVIEW

**Comment by andronoob** [comment]
>These warning texts are really hard to write...

I'm afraid to say that... the user would probably have a headache as well.

I still think such compromise is just a temporary expedient, until real solution (standardized multi-part/fountain code QR code for transferring large PSBT, which allows feeding/requiring full previus tx data of all inputs) comes out.

**Comment by ecdsa** [comment]
> These warning texts are really hard to write...

Maybe the third message could be improved:

> "Warning: The fee could not be verified. All inputs are segwit, so as long as you only sign this transaction once, you are safe."

This is a bit misleading. First, the issue is not that the fee could not be verified. As a matter of fact, the fee was verified; the issue is that this verification will break apart if we sign it more than once. Second, it does not make things clearer to state that "all inputs are segwit", because segwit is already the best input type we have. (I would mention it only when we have taproot, to encourage switching to taproot).

May I suggest this instead:
> "Warning: If you received this transaction from an untrusted device, do not accept to sign it more than once."

**Comment by SomberNight** [comment]
> "Warning: If you received this transaction from an untrusted device, do not accept to sign it more than once."

It's not clear from that what could happen though. It's the fee where the user could end up overpaying.
So maybe append "Otherwise you could up paying a different fee."

**Comment by ecdsa** [comment]
sorry, abac4a4 has a wrong commit message

**Pull request merged**
