### PR TITLE
Add a warning about harmful code to the console

### PR DESCRIPTION
**Pull request by bauerj**
This adds a warning about malicious code to the console window. It should help prevent users from executing code they found online.

## Screenshots

This warning is certainly hard to miss:
python_2018-01-12_00-08-25

Clicking the message indeed hides it:
python_2018-01-12_00-08-31

Related: #3678

### CODE REVIEW

**Comment by SomberNight** [comment]
Tested, looks good.


Though depending on QT version, the last line is sometimes not shown; and the text is not wrapped.
Not sure these are worth fixing, unless they are one-liners.

-----
All pics on Debian 9.

### PyQt 5.7

pic3
pic4

### PyQt 5.9

pic1
pic5

**Comment by bauerj** [comment]
Thanks for testing! I didn't find a way to automatically increase the size of the label based on the content size. However, I've enabled word wrapping and increased the height slightly so it should be at least better now.

**Comment by ecdsa** [comment]
do we want the hidden state to be remembered?

**Comment by bauerj** [comment]
Not sure about that. The console is seldom used so the benefit wouldn't be big.
But users might forget that they disabled that warning. I'd rather have the warning after every restart.

**Comment by dabura667** [comment]
No.

People forget.

I don’t mind that Facebook always greets me with a huge DONT PASTE STUFF HERE message.

As long as it doesn’t cover up server banners I say persist for the session until the GUI is closed

**Comment by SomberNight** [comment]
@ecdsa Do you mean clicking it once would hide it forever? It's very easy to click it even by mistake.

@dabura667 Well it covers up server banners somewhat (now more than on above screenshots). But I think the behaviour in the PR of "click it once, and it won't be shown until you re-open Electrum" is fine.

**Pull request merged**
