### PR TITLE
Properly handle invalid payment request URLs

### PR DESCRIPTION
**Pull request by alexander255**
Otherwise the client would simply hang when receiving an invalid URL dumping a hard-to-read exception to the terminal.

While this is an improvement over the previous situation (and therefor should be merged), it doesn't actually address the underlying that caused this situation in the first place: Coinbase uses payment request URLs for their processing, but also Cloudflare for their webservers. Considering how easy was to enable TOR in my Electrum instance I'd definitely call this a series of unfortunate circumstances. I'm not sure what to do about that through…

### CODE REVIEW

**Comment by ecdsa** [comment]
thanks. why is the if...else statement instide the try...except block?

**Comment by alexander255** [comment]
That's the original implementation (the `try`…`catch` got added later), when I realized that it's not the only way the request can fail.
Basically it checks whether the server actually understood the request or just blurted out some default response (as Anti-DDoS-sites, captive portals, badly configured webservers in general tend to do).
Unless I'm mistaken this behaviour is also required by [`bip-0071`](https://github.com/bitcoin/bips/blob/d2a8fb089d7010d839530f879e07edc4e48b84fa/bip-0071.mediawiki):

> A **web server generating a PaymentRequest** message to initiate the payment protocol **would precede the binary message data with the following headers**:
> 
>     Content-Type: application/bitcoin-paymentrequest
>     Content-Transfer-Encoding: binary

**Comment by ecdsa** [comment]
thank you, I merged it.
I think you did not understand my question, though.

**Comment by alexander255** [comment]
Now that you mention it 😛 
Anyway I just though about it again and putting the `if`…`else` inside the `try`…`catch` makes sense since it makes sure that `response` is always available and represents a successful HTTP response when the `if`…`else` is reached. If the `if`…`else` where to be put after the `try`…`catch` and `url` would fail to resolve entirely (because it was bogus mainly), then `response` would never be set and `electrum` would end up in that "looks like its hanging"-state again due to the second crash when `response` is "used before assignment".

**Comment by alexander255** [comment]
Semi-related: Should I submit a patch that converts the current `raise BaseException("unknown scheme")` to an UI displayable error as well?

**Pull request merged**
