### PR TITLE
integrate PSBT support natively. WIP

### PR DESCRIPTION
**Pull request by SomberNight**
This PR integrates [PSBT](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) support into the main codebase.

Design decisions taken:
- We completely drop support for the existing custom partial tx format.
  - Users will need to upgrade all their cosigners at the same time.
  - This greatly simplifies the code (and the UI/UX).
- Allow insecure signing of legacy inputs without full previous tx. This retains small QR code sizes (and QR codes being possible in the first place!) for txns with legacy inputs.
  - Note that full previous txns can be rather large, just consider trying to spend from a batched exchange withdrawal.
  - With the current custom partial tx format Electrum has been using for many years, full previous txns were never included. The GUI has been displaying "fee" as "unknown".
  - When importing a PSBT that has a legacy input and no corresponding NON_WITNESS_UTXO, we allow signing (against bip174 spec).
    - The Qt GUI
      - If there is a WITNESS_UTXO, shows the fee along with a warning icon with an explanatory tooltip.
      - If there is no WITNESS_UTXO, shows fee as "unknown".
    - The Kivy GUI shows fee as "unknown".
  - When exporting a PSBT, the spec is followed; except when "showing" a QR code, in which case all NON_WITNESS_UTXOs are converted to WITNESS_UTXOs.
- To try to preserve user privacy in serialized txns, the PSBT_GLOBAL_XPUB fields are rarely populated. Further, in PSBT_IN_BIP32_DERIVATION and PSBT_OUT_BIP32_DERIVATION fields, the derivation prefix (typically the hardened part of the path) is often not included.
  - When exporting a PSBT (clipboard, file, qrcode), there are three options offered (in the Qt GUI).
    - The "main"/typical export option (the only option in Kivy/CLI) does not put any xpubs into the psbt, and does not include derivation prefixes.
    - The "coinjoin" export option strips every GLOBAL field and every per-output field, and also strips the PSBT_IN_BIP32_DERIVATION field from the inputs.
    - The coldcard plugin adds another export option that puts xpubs into the psbt, and includes full derivation paths.
  - At the beginning of the tx signing flow, we put global xpubs into the transaction, and also put full derivation paths for the inputs and outputs where we know them. At the end of the signing flow, the xpubs are removed and the full paths are replaced with derivation suffixes.
    - This is done as hardware wallets need the full paths during signing.
    - Further, some signers, e.g. hardware wallets, might want the global xpubs, e.g. when signing multisig inputs. Signing multisig inputs for stateless signers is not secure without xpubs (specifically the change detection part).
- Related to the previous point, note that in the wallet creation wizard, there has been no option to specify a derivation prefix or a root fingerprint. This is still the case, and dealing with this is now postponed for later. (See https://github.com/spesmilo/electrum/issues/5715) Further note that even if we introduced a way to specify these, it is important not to make it mandatory, as this is actually a privacy leak between cosigners.
  - If we do not have a derivation prefix or root fingerprint for a key, we use the fingerprint of the intermediate bip32 node, and put the derivation suffix as the path. Technically, this is not against the spec, and if another Updater/Signer is smart enough, they can detect what is going on (Electrum of course does detect this).
- Upgrading wallet files. Again, related to the previous point(s), existing wallet files do not store root fingerprints and derivation prefixes.
  - If the depth (of the intermediate xpub) is shallow enough, 0 or 1, such as with Electrum seeds, then we can, just from the xpub, reconstruct the root fp and the der prefix.
  - For deeper depths, the missing fields are explicitly set to None, and the code handles None values for these.
  - For hardware wallets, existing wallets store the derivation prefix (as hww has always needed this) but not the root fingerprint. The root fp is opportunistically populated the next time the user connects their device.
- Encoding.
  - When importing files/text/qrcodes, we accept many possibilities, including raw bytes, hex strings, base64 text irrespective of medium (notably base64 text in a file is accepted, which should probably also be mandated by the spec itself...)
  - When exporting, we respect the spec, and clipboard gets base64 text, while saving to file uses raw bytes.
  - As before, transactions are encoded as base43 when displayed in a QR code. (see https://github.com/spesmilo/electrum/issues/5746)
    - This rule is relaxed on the QR-reader side now: when decoding, accept anything we recognise.
- Input finalizer. This implementation can only [finalize inputs](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#input-finalizer) that are "ismine" to the wallet. Relatedly, transaction size estimation when there are not-yet-finalized not-ismine inputs is not really good.
  - This is because input finalizing and input size estimation relies on the wallet side-effecting tx objects by adding all kinds of data to the inputs (in `add_input_info`).

-----

- [x] figure out something about https://github.com/spesmilo/electrum/issues/5715
- [x] add tests for trustedcoin legacy tx serialization
- [x] re-add CLI command "serialize"
- [ ] ~~some performance issues with large wallets atm~~ (maybe later)
- [x] fix offline signing beyond gap limit
- [x] opportunistically learn root fingerprint of existing hardware keystores
- [x] remove global xpubs and bip32 der prefixes from psbt after signing

closes https://github.com/spesmilo/electrum/issues/4615
closes https://github.com/spesmilo/electrum/issues/4514
closes https://github.com/spesmilo/electrum/pull/5671
closes https://github.com/spesmilo/electrum/pull/4883
closes https://github.com/spesmilo/electrum/pull/5717
closes https://github.com/spesmilo/electrum/issues/4322
closes https://github.com/spesmilo/electrum/issues/3302

### CODE REVIEW

**Comment by SomberNight** [comment]
Note: one "feature" of the present implementation is that we can only [finalize inputs](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#input-finalizer) that are "ismine". Input finalizing works through the wallet side-effecting tx objects by adding all kinds of data to inputs (in `add_input_info`).
To be able to finalize not ismine inputs, we would need to hardcode templates in the transaction logic to recognise known script types (p2pkh, p2wpkh, multisig types, etc).
Another thing that currently relies on the wallet side-effecting ismine inputs is input size estimation. We only have "good" estimates for ismine inputs.

I don't believe this is a crucial issue to be fixed, rather a nice-to-have, hence it is not a blocker.

**Comment by ecdsa** [comment]
Thanks a lot for this outstanding work.
I have one more question:
does Coldcard require a global xpub in order to sign non-multisig inputs?

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/pull/5721/commits/1017fefdc95738aeb99a165e80104a0efe35992a

**Comment by craigraw** [comment]
Picked up a couple of issues when testing:

- Tools -> Load Transaction -> From file does not accept binary PSBT files (trivial fix)
- Error when loading a fully signed (multisig) PSBT: "SerializationError(error('unpack_from requires a buffer of at least 4 bytes'))"

Should the *.txn option be removed from the file selection dialogs?

**Comment by SomberNight** [comment]
@craigraw Thanks for testing!
I've pushed some changes to address your findings:
https://github.com/spesmilo/electrum/commit/85a4811742e641828ee8fa45115e8ef99ca9bdbd
https://github.com/spesmilo/electrum/commit/9ff7d2c5a70298da885e5917b39f79cccb16dbaa
https://github.com/spesmilo/electrum/commit/365aa189f274970ef2f4446f6e89b429e41b4ae5

> Should the *.txn option be removed from the file selection dialogs?

Well, with what file extension do you suggest we save fully signed (non-psbt) transactions?
We have been using .txn in the past, it seemed to make sense to keep using that for these.
Further, these fully signed transactions are saved as hex strings, not raw bytes; just like before.
Hex strings are more human-friendly, both for debugging and for easy copy-pasting, and as they are strings they are even easier to interact with in shell.
We can change this though if you have a better suggestion.
@ecdsa 

> Error when loading a fully signed (multisig) PSBT: "SerializationError(error('unpack_from requires a buffer of at least 4 bytes'))"

I am not fully sure about this; it might be already fixed by the above commits; if not, please give more details or share the psbt.

**Comment by craigraw** [comment]
Thanks, I now understand that a .psbt will be exported for a partially signed transaction, and a .txn for a fully signed one. The file selection dialog had me a little confused - it's now much clearer with your recent commits. 

One note is that you can't currently load a .txn from the Load Transaction -> From file (it fails with the SerializationError I mentioned before) - it does however work using Load Transaction -> From text.

**Comment by SomberNight** [comment]
> One note is that you can't currently load a .txn from the Load Transaction -> From file (it fails with the SerializationError I mentioned before) - it does however work using Load Transaction -> From text.

Thanks again. Should work now with https://github.com/spesmilo/electrum/commit/bf8a58c0b49528573b9651b7a27a4168ec5985f7

**Comment by craigraw** [comment]
Thanks, confirmed fixed.

**Pull request merged**
