### PR TITLE
Digital Bitbox hardware wallet plugin

### PR DESCRIPTION
**Pull request by douglasbakkum**
Hello! This PR adds support for the Digital Bitbox hardware wallet (digitalbitbox.com). The PR follows the templates of the other hardware wallet plugins as much as possible, and no external git repositories are required. 

We have read and accept the [Plugin Rules](https://github.com/digitalbitbox/electrum/blob/master/plugins/README).

### CODE REVIEW

**Comment by ecdsa** [comment]
thanks!

**Comment by Sarakay87** [comment]
How do I claim

**Comment by ecdsa** [comment]
I'm testing this now, sorry for the delay.
```
  File "hid.pyx", line 71, in hid.device.open_path (hid.c:1714)
IOError: open failed
```
do I need to initialize the device first with the software downloaded from your website?

**Comment by douglasbakkum** [comment]
Thanks.

It does not need to be initialized, but if you are on Linux, you would need to adjust the USB permissions. Sorry, forgot to mention that. Copying from our website:


> If the Digital Bitbox device is not detected by the app, you may need to manually adjust USB permissions. To do this for most recent distributions, enter the following line in a terminal (sudo access required):
```
$ printf "SUBSYSTEM==\"usb\", TAG+=\"uaccess\", TAG+=\"udev-acl\", SYMLINK+=\"dbb%n\", ATTRS{idVendor}==\"03eb\", ATTRS{idProduct}==\"2402\"\n" | sudo tee /etc/udev/rules.d/51-hid-digitalbitbox.rules > /dev/null
```
> Or, if the above does not work for your distribution, add yourself to the 'plugdev' group (if not already a member; a reboot may be required for some distributions) and enter the following line in a terminal (sudo access required):
```
$ printf "SUBSYSTEM==\"usb\", SYMLINK+=\"dbb%n\", GROUP=\"plugdev\", MODE=\"0664\", ATTRS{idVendor}
```

**Comment by ecdsa** [comment]
oh right, I should have known..

**Comment by ecdsa** [comment]
merged after minor changes. Please check ae0235ee6290a1b190ef56d174a28b5dffdf8405 
I removed the call to hashlib.pbkdf2_hmac because older versions of python do not have it.

**Comment by douglasbakkum** [comment]
Great! Will check out the changes as soon as I get a chance - traveling at the moment with limited access.

**Comment by douglasbakkum** [comment]
tested ACK
Thanks a lot!

**Pull request closed without merging**
