### PR TITLE
Add BTCe exchange

### PR DESCRIPTION
**Pull request by lzsaver**
These commits add BTCe exchange and sort the order of exchanges in corresponding files.

### CODE REVIEW

**Comment by lzsaver** [comment]
Will someone review? Thanks in advance.

**Comment by lzsaver** [comment]
The reason for which it was decided to sort all the ExchangeBase-classes is that their non-alphabetical order complicates the navigation in the code.

**Comment by EagleTM** [comment]
Thanks for the pull request. It takes a lot longer to review when you do more changes in one PR. If you are looking for a fast merge, separate adding BTCe from changing the sort order in two PR. The former can be merged fast.

**Comment by ecdsa** [comment]
are you aware that currencies.json is generated automatically?
I added it to the repo for convenience, but you are not supposed to edit it

**Comment by ecdsa** [comment]
closing; I cherry-picked the commits that were useful.

**Pull request closed without merging**
