### PR TITLE
config: keep wallets directory stable, regardless of wallet opens in …

### PR DESCRIPTION
**Pull request by accumulator**
config: keep wallets directory stable, regardless of wallet opens in other directories

addresses issue #8028

### CODE REVIEW

**Comment by SomberNight** [comment]
In the context of subdirectories inside the main `wallets/` folder, I agree this is probably an improvement.

However, also consider saving wallets to some unrelated path. E.g. imagine a user creating `~/dropbox/my_electrum_wallets/` or similar. Say they have all their existing wallet files in that folder. When they click `New/Restore` or `Open`, what is the reasonable thing to do? Is it to use `~/.electrum/wallets/` or `~/dropbox/my_electrum_wallets/`?

-----

An alternative idea would be to customise the default value in `WCWalletName.name_e`.
wizard_wallet_name
If the abs path is a subpath of `~/.electrum/wallets/`, we could show only the relative path,
otherwise we could show the full abs path.

That is,
`~/.electrum/wallets/wallet_47` -> `wallet_47`
`~/.electrum/wallets/lnfun/wallet_47` -> `lnfun/wallet_47`
`~/dropbox/my_electrum_wallets/` -> `~/dropbox/my_electrum_wallets/`  (or resolve the tilde; that's besides the point)

-----

Or as suggested in the linked issue, just do:
> one solution would be for the New/Restore wallet wizard to display the current root path above the path entry field, so the user can take any unexpected changes into account

(and maybe hide the dir path if it is `~/.electrum/wallets/`)

**Comment by SomberNight** [comment]
Side-note, try:
- create a wallet at `/opt/tmp/w1`, set a password and encrypt file
- close program
- start electrum, wizard opens, `WCWalletName.name_e` is prefilled with `w1`
    - if I enter the password and press `Finish`, wallet at `/opt/tmp/w1` opens
    - if I change `WCWalletName.name_e` to `w2` and create a new wallet, it gets created at `~/.electrum/wallets/w2`
    - kind of confusing

This is already the behaviour on existing master; unaffected by this PR.

**Comment by accumulator** [comment]
> In the context of subdirectories inside the main `wallets/` folder, I agree this is probably an improvement.
> 
> However, also consider saving wallets to some unrelated path. E.g. imagine a user creating `~/dropbox/my_electrum_wallets/` or similar. Say they have all their existing wallet files in that folder. When they click `New/Restore` or `Open`, what is the reasonable thing to do? Is it to use `~/.electrum/wallets/` or `~/dropbox/my_electrum_wallets/`? (e.g. see #8495)

In the absence of a user definable wallet folder preference setting (so the wallets dir can be separate from the data dir), we only have the `-D/--dir` cmdline option for that (which also keeps wallets together with config and other runtime files). Creating a separate cmdline option for this pref setting might be useful.

BTW, the cmdline descriptions for` -D, -w` are somewhat confusing, and could be improved (e.g 'electrum path' can be interpreted in a few different ways, 'wallet path' could mean a folder or a file, etc..)

> An alternative idea would be to customise the default value in `WCWalletName.name_e`. wizard_wallet_name If the abs path is a subpath of `~/.electrum/wallets/`, we could show only the relative path, otherwise we could show the full abs path.

Yes this would be logical.

> That is, `~/.electrum/wallets/wallet_47` -> `wallet_47` `~/.electrum/wallets/lnfun/wallet_47` -> `lnfun/wallet_47` `~/dropbox/my_electrum_wallets/` -> `~/dropbox/my_electrum_wallets/` (or resolve the tilde; that's besides the point)
> 
> Or as suggested in the linked issue, just do:
> 
> > one solution would be for the New/Restore wallet wizard to display the current root path above the path entry field, so the user can take any unexpected changes into account
> 
> (and maybe hide the dir path if it is `~/.electrum/wallets/`)

**Comment by accumulator** [comment]
> EDIT: Ah! but it is not the behaviour on 4.4.6, where it creates w2 at `/opt/tmp/w2`. I guess this is a ~regression from the wizard refactor.

It depends from which electrum window the New/Restore is triggered from. I don't think this was changed by the new wizard, as the current window's wallet path was used before as well.

**Comment by SomberNight** [comment]
> > EDIT: Ah! but it is not the behaviour on 4.4.6, where it creates w2 at `/opt/tmp/w2`. I guess this is a ~regression from the wizard refactor.
> 
> It depends from which electrum window the New/Restore is triggered from. I don't think this was changed by the new wizard, as the current window's wallet path was used before as well.

I am talking about directly opening into the wizard, before any main window exists. That is, clean start of electrum, `config.GUI_LAST_WALLET="/opt/tmp/w1"`, which is encrypted, so the wizard opens and prompts for password. The `WCWalletName.name_e` lineedit then shows `w1`, and if I change it to `w2` (instead of entering the pw), then it creates `w2` in a completely different folder than where `w1` is. This is changed between master and 4.4.6.
Anyway, it's not too important; but I would argue it's a bug :)

> In the absence of a user definable wallet folder preference setting (so the wallets dir can be separate from the data dir), we only have the -D/--dir cmdline option for that (which also keeps wallets together with config and other runtime files). Creating a separate cmdline option for this pref setting might be useful.

I don't know... sounds overkill to have another option for this.

**Comment by accumulator** [comment]
> > > EDIT: Ah! but it is not the behaviour on 4.4.6, where it creates w2 at `/opt/tmp/w2`. I guess this is a ~regression from the wizard refactor.
> > 
> > 
> > It depends from which electrum window the New/Restore is triggered from. I don't think this was changed by the new wizard, as the current window's wallet path was used before as well.
> 
> I am talking about directly opening into the wizard, before any main window exists. That is, clean start of electrum, `config.GUI_LAST_WALLET="/opt/tmp/w1"`, which is encrypted, so the wizard opens and prompts for password. The `WCWalletName.name_e` lineedit then shows `w1`, and if I change it to `w2` (instead of entering the pw), then it creates `w2` in a completely different folder than where `w1` is. This is changed between master and 4.4.6. Anyway, it's not too important; but I would argue it's a bug :)

In this branch it shows an absolute path now if the last wallet is outside the datadir wallets subtree


> > In the absence of a user definable wallet folder preference setting (so the wallets dir can be separate from the data dir), we only have the -D/--dir cmdline option for that (which also keeps wallets together with config and other runtime files). Creating a separate cmdline option for this pref setting might be useful.
> 
> I don't know... sounds overkill to have another option for this.

Yeah I'm fine with just having `--dir` too.

**Comment by accumulator** [comment]
any objections left on this PR?

**Pull request merged**
