### PR TITLE
Add support for Ledger Nano S Plus

### PR DESCRIPTION
**Pull request by nndiaye-ledger**

### CODE REVIEW

**Comment by SomberNight** [comment]
Hi. Thanks for the PR.

Could you link to some some Ledger doc or source code that mentions these integers -- or maybe someone who is a publicly visible member of the https://github.com/LedgerHQ github org, or @btchip could confirm either the integers or that you really work for Ledger :)

**Comment by nndiaye-ledger** [comment]
Hi @SomberNight :) , 

Here is the definition of Nano S Plus on ledgerjs:
https://github.com/LedgerHQ/ledgerjs/blob/master/packages/devices/src/index.ts#L42-L64

BR

**Comment by SomberNight** [comment]
Looks good, thanks.

**Comment by gruve-p** [comment]
@nndiaye-ledger https://github.com/spesmilo/electrum/blob/master/contrib/udev/20-hw1.rules needs to be updated also to include Nano S plus

**Comment by gruve-p** [comment]
https://github.com/spesmilo/electrum/pull/7698 created

**Pull request merged**
