### PR TITLE
Add tab icons

### PR DESCRIPTION
**Pull request by bauerj**
This adds an icon to each tab in the main window which will hopefully improve usability.

Screenshot
===
python_2017-07-02_23-52-01

Icon source
===

The icons are part of [_fontawesome_](http://fontawesome.io/license/):

History
http://fontawesome.io/icon/list

Send
http://fontawesome.io/icon/paper-plane

Receive
http://fontawesome.io/icon/download

Addresses
http://fontawesome.io/icon/book

Contacts
http://fontawesome.io/icon/address-book

Coins
http://fontawesome.io/icon/money

Console
http://fontawesome.io/icon/bolt

### CODE REVIEW

**Comment by ecdsa** [comment]
not sure if I really like it..
it adds more complexity to the GUI

**Comment by bauerj** [comment]
My opinion is that clear icons make it easier to find the right tab.

**Comment by ecdsa** [comment]
icons

**Comment by bauerj** [comment]
New icons: 
python_2017-07-09_00-29-04

**Comment by MaxXor** [comment]
I'd prefer the colorful icons as they are more easy distinguishable and also match the existing transaction icons.

**Comment by EagleTM** [comment]
I like the colorful icons and think most users would enjoy them.

Compromise could be to make it a config setting, so you can switch it off by selecting "minimal visual effects". This setting could be used for other beautifications in the future which might be seen as less slick to purists.

**Comment by ecdsa** [comment]
thanks; it's better with color

**Pull request merged**
